namespace SafeRide.Domain.Enums;

public enum TripTerminationCategory { STANDARD, SAFETY }
public enum SafetyPaymentReconciliationStatus { NOT_REQUIRED, PAYMENT_PENDING, PAID, REFUND_PENDING, REFUNDED }
public enum ManualRefundStatus { REFUND_PENDING, REFUNDED }
public enum PreTripCheckResult { PASS, FAIL }
public enum VehicleFaultType { BRAKE_FAILURE, LIGHT_FAILURE, TIRE_FAILURE, STEERING_FAILURE, ENGINE_FAILURE, ELECTRICAL_FAILURE, OTHER }
public enum SafetyReportType { GENERAL, UNSAFE_CUSTOMER, VEHICLE_ISSUE }
public enum UnsafeCustomerReason { DISTRACTING, VIOLENT, INTERFERING_WITH_VEHICLE, UNSAFE_REQUEST, OTHER }
public enum AccidentCategory { DRIVER_INJURY, CUSTOMER_VEHICLE_DAMAGE, THIRD_PARTY_DAMAGE, MULTIPLE }
public enum AccidentStatus { REPORTED, EVIDENCE_COLLECTION, UNDER_REVIEW, LIABILITY_PENDING, SETTLEMENT, CLOSED, REJECTED }
// Intoxication is evidence/context, not an independent cause for assigning customer liability.
public enum AccidentRootCause { DRIVER_ERROR, CUSTOMER_INTERFERENCE, THIRD_PARTY_ERROR, VEHICLE_MECHANICAL_FAILURE, VEHICLE_PRE_EXISTING_DEFECT, ROAD_CONDITION, WEATHER, FORCE_MAJEURE, UNKNOWN }
public enum ResponsiblePartyType { DRIVER, CUSTOMER, THIRD_PARTY, VEHICLE, OBJECTIVE }
public enum VehicleDefectAwareness { UNKNOWN, CUSTOMER_KNEW, DRIVER_KNEW, BOTH_KNEW, NEITHER_COULD_REASONABLY_KNOW }
public enum DriverFaultLevel { NO_FAULT, ORDINARY_NEGLIGENCE, GROSS_NEGLIGENCE, INTENTIONAL_MISCONDUCT }
public enum LiabilityAssessmentStatus { DRAFT, PENDING_CONFIRMATION, CONFIRMED, DISPUTED }
public enum ProtectionClaimStatus { DRAFT, UNDER_REVIEW, APPROVED, PENDING_FUNDING, FUNDED, RECOVERY_IN_PROGRESS, SETTLED, CLOSED, REJECTED }
public enum DriverLiabilityStatus { CONFIRMED, DISPUTED, PARTIALLY_PAID, PAID, WAIVED }
public enum RiskFundTransactionType { OPENING_BALANCE, CONTRIBUTION, CLAIM_ADVANCE, CLAIM_PAYOUT, DRIVER_RECOVERY, CUSTOMER_RECOVERY, THIRD_PARTY_RECOVERY, INSURANCE_RECOVERY, ADJUSTMENT }
public enum LedgerDirection { CREDIT, DEBIT }
public enum RecoverySourceType { DRIVER, CUSTOMER, THIRD_PARTY, INSURANCE }
public enum ClaimReconciliationType { ADVANCE_WRITE_OFF }
public enum VehicleInsuranceType { MANDATORY_TPL, PHYSICAL_DAMAGE, OTHER }
public enum InsuranceVerificationStatus { PENDING, VERIFIED, REJECTED, EXPIRED }
public enum InsuranceClaimStatus { NOT_SUBMITTED, PENDING, APPROVED, REJECTED }
public enum InsurancePaymentDestination { DIRECT_TO_CLAIMANT, REIMBURSE_RISK_FUND }
public enum InsuranceProviderOperation { CALCULATE, SUBMIT, GET_STATUS, APPROVE, REJECT }
public enum AccidentEvidenceType { PHOTO, DOCUMENT, DRIVER_STATEMENT, CUSTOMER_STATEMENT, THIRD_PARTY_INFORMATION, POLICE_REPORT }
