import { useMemo, useState } from 'react';
import { AdminLayout } from '../../shared/layouts/AdminLayout';
import useFetch from '../../shared/hooks/useFetch';
import ActionFeedback from '../../shared/components/ActionFeedback/ActionFeedback';
import { getCustomerNoShows, getCustomerNoShowDetail, exemptCustomerNoShow, clearCustomerBookingRestriction } from '../../features/staff/noShows/staffNoShowsApi';
import './CustomerNoShowsPage.css';

const fmt = (value) => value ? new Date(value).toLocaleString('vi-VN') : '—';
function CustomerNoShowsPage() {
  const [filters, setFilters] = useState({ status: '', customerId: '', from: '', to: '' });
  const [page, setPage] = useState(1); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState('');
  const path = useMemo(() => { const q = new URLSearchParams({ ...filters, page, pageSize: 20 }); return `/staff/customer-no-shows?${q}`; }, [filters, page]);
  const list = useFetch(path);
  const open = async (id) => { setFeedback(''); setSelected({ loading: true }); try { setSelected(await getCustomerNoShowDetail(id)); } catch (e) { setFeedback(e.message); setSelected(null); } };
  const action = async (fn) => { const reason = window.prompt('Nhập lý do review:'); if (!reason?.trim()) return; setBusy(true); setFeedback(''); try { await fn(reason.trim()); setFeedback('Đã cập nhật review.'); await list.refetch(); if (selected?.event?.eventId) await open(selected.event.eventId); } catch (e) { setFeedback(e.message); } finally { setBusy(false); } };
  const items = list.data?.items ?? [];
  return <AdminLayout><header className="page-header"><h1 className="page-title">Duyệt no-show khách hàng</h1><p className="page-subtitle">Kiểm tra bằng chứng và khôi phục quyền đặt chuyến khi cần.</p></header>
    <div className="noshow-filters"><input placeholder="Customer ID" value={filters.customerId} onChange={e => { setFilters({ ...filters, customerId: e.target.value }); setPage(1); }} /><select value={filters.status} onChange={e => { setFilters({ ...filters, status: e.target.value }); setPage(1); }}><option value="">Tất cả trạng thái</option><option value="VERIFIED">VERIFIED</option><option value="EXEMPTED">EXEMPTED</option><option value="REVERSED">REVERSED</option></select><input type="date" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value })} /><input type="date" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value })} /></div>
    <ActionFeedback message={feedback || (list.error && String(list.error))} variant={list.error || feedback && feedback.startsWith('HTTP') ? 'error' : 'success'} />
    {list.isLoading ? <div className="noshow-empty">Đang tải dữ liệu...</div> : <div className="noshow-table-wrap"><table className="noshow-table"><thead><tr><th>Trạng thái</th><th>Khách hàng</th><th>Tài xế</th><th>Booking / Trip</th><th>Khoảng cách</th><th>Thời gian</th><th></th></tr></thead><tbody>{items.map(x => <tr key={x.eventId}><td><span className={`noshow-status noshow-status--${String(x.status).toLowerCase()}`}>{x.status}</span></td><td>{x.customerName}<small>{x.customerId}</small></td><td>{x.driverName}<small>{x.driverId}</small></td><td>#{x.bookingId} / #{x.tripId}</td><td>{x.arrivalDistanceMeters == null ? '—' : `${x.arrivalDistanceMeters} m`}</td><td>{fmt(x.verifiedAt || x.driverReportedAt)}</td><td><button type="button" onClick={() => open(x.eventId)}>Xem chi tiết</button></td></tr>)}{!items.length && <tr><td colSpan="7" className="noshow-empty">Không có sự kiện no-show.</td></tr>}</tbody></table></div>}
    <div className="noshow-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Trước</button><span>Trang {list.data?.page ?? page} / {list.data?.totalPages ?? 1}</span><button disabled={page >= (list.data?.totalPages ?? 1)} onClick={() => setPage(page + 1)}>Sau</button></div>
    {selected && <div className="noshow-overlay" onClick={() => setSelected(null)}><section className="noshow-modal" onClick={e => e.stopPropagation()}>{selected.loading ? <p>Đang tải chi tiết...</p> : <><button className="noshow-close" onClick={() => setSelected(null)}>×</button><h2>No-show #{selected.event.eventId}</h2><p><b>Customer:</b> {selected.event.customerName} | <b>Driver:</b> {selected.event.driverName}</p><p><b>Booking/Trip:</b> #{selected.event.bookingId} / #{selected.event.tripId}</p><div className="noshow-evidence"><b>GPS:</b> {selected.event.arrivalLatitude ?? '—'}, {selected.event.arrivalLongitude ?? '—'}<br /><b>Distance:</b> {selected.event.arrivalDistanceMeters ?? '—'} m<br /><b>Arrived:</b> {fmt(selected.event.arrivedAt)}<br /><b>Reminder:</b> {fmt(selected.event.reminderSentAt)}<br /><b>Wait satisfied:</b> {fmt(selected.event.waitSatisfiedAt)}<br /><b>Verified:</b> {fmt(selected.event.verifiedAt)}<br /><b>Reason:</b> {selected.event.reviewReason || '—'}</div><h3>Booking privilege</h3><p>{selected.privilege ? `Level: ${selected.privilege.restrictionLevel} | No-show: ${selected.privilege.verifiedNoShowCount} | Rate: ${(selected.privilege.noShowRate * 100).toFixed(1)}% | Streak: ${selected.privilege.consecutiveNoShowStreak}` : 'Chưa có dữ liệu'}</p>{selected.supports?.length > 0 && <p>Driver support: {selected.supports.map(s => `${s.supportAmount} VND (${s.status})`).join(', ')}</p>}<div className="noshow-actions"><button disabled={busy || selected.event.status !== 'VERIFIED'} onClick={() => action(r => exemptCustomerNoShow(selected.event.eventId, r))}>{selected.event.status === 'EXEMPTED' ? 'Đã miễn trừ' : 'Miễn trừ no-show'}</button>{selected.privilege && (selected.privilege.scheduledRestrictedUntil || selected.privilege.bookingCooldownUntil) && <button disabled={busy} onClick={() => action(r => clearCustomerBookingRestriction(selected.event.customerId, r))}>Gỡ hạn chế hiện tại</button>}</div><small>Gỡ hạn chế hiện tại không xóa lịch sử no-show.</small></>}</section></div>}</AdminLayout>;
}
export default CustomerNoShowsPage;
