// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class AspNetUser : IdentityUser<Guid>
{
    public string? FullName { get; set; }
    public string? AvatarUrl { get; set; }
    public bool IsActive { get; set; }
    public string? BanReason { get; set; }

    public string? Gender { get; set; }
    public DateOnly? DateOfBirth { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> BookingCancelledByNavigations { get; set; } = new List<Booking>();

    public virtual ICollection<Booking> BookingCustomers { get; set; } = new List<Booking>();

    public virtual ICollection<DriverKyc> DriverKycs { get; set; } = new List<DriverKyc>();

    public virtual DriverProfile? DriverProfile { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<SOSAlert> SOSAlertResolvedByUsers { get; set; } = new List<SOSAlert>();

    public virtual ICollection<SOSAlert> SOSAlertTriggeredByUsers { get; set; } = new List<SOSAlert>();

    public virtual ICollection<TripShare> TripShareRecipientUsers { get; set; } = new List<TripShare>();

    public virtual ICollection<TripShare> TripShareSharedByUsers { get; set; } = new List<TripShare>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();

    public virtual ICollection<AspNetRole> Roles { get; set; } = new List<AspNetRole>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();
}
public class AspNetRole : IdentityRole<Guid>
{
    // Thêm Description để chú thích role này làm gì (VD: "Quản trị viên hệ thống")
    public string? Description { get; set; }

    public virtual ICollection<AspNetUser> Users { get; set; } = new List<AspNetUser>();
}