// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("IsActive", Name = "IX_AspNetUsers_IsActive")]
[Index("NormalizedEmail", Name = "IX_AspNetUsers_NormalizedEmail")]
public partial class AppUser : IdentityUser<Guid>
{
    [StringLength(250, MinimumLength = 2, ErrorMessage = "Full name must be between 2 and 250 characters")]
    public string? FullName { get; set; }

    [StringLength(500, ErrorMessage = "Avatar URL cannot exceed 500 characters")]
    [Url(ErrorMessage = "Avatar URL must be a valid URL")]
    public string? AvatarUrl { get; set; }

    // Profile fields
    [StringLength(10, ErrorMessage = "Gender cannot exceed 10 characters")]
    [RegularExpression("^(Male|Female|Other)$", ErrorMessage = "Gender must be Male, Female, or Other")]
    [Unicode(false)]
    public string? Gender { get; set; }

    [DataType(DataType.Date, ErrorMessage = "Date of birth must be a valid date")]
    public DateOnly? DateOfBirth { get; set; }

    [Required(ErrorMessage = "Active status is required")]
    public bool IsActive { get; set; }

    [StringLength(500, ErrorMessage = "Ban reason cannot exceed 500 characters")]
    public string? BanReason { get; set; }

    [Required(ErrorMessage = "Created date is required")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }

    // Refresh Token
    [StringLength(4096, ErrorMessage = "Refresh token cannot exceed 4096 characters")]
    public string RefreshToken { get; set; } = string.Empty;

    public DateTime? RefreshTokenExpiryTime { get; set; }


    // --- Navigation Properties ---
    [InverseProperty("Driver")]
    public virtual ICollection<DriverKyc> DriverKycs { get; set; } = new List<DriverKyc>();
    [InverseProperty("Driver")]
    public virtual DriverProfile? DriverProfile { get; set; }
    [InverseProperty("User")]
    public virtual ICollection<Otpverification> Otpverifications { get; set; } = new List<Otpverification>();

    [InverseProperty("CancelledByNavigation")]
    public virtual ICollection<Booking> BookingCancelledByNavigations { get; set; } = new List<Booking>();

    [InverseProperty("Customer")]
    public virtual ICollection<Booking> BookingCustomers { get; set; } = new List<Booking>();

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

  
    [InverseProperty("Customer")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [InverseProperty("User")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("ResolvedByUser")]
    public virtual ICollection<SOSAlert> SosalertResolvedByUsers { get; set; } = new List<SOSAlert>();

    [InverseProperty("TriggeredByUser")]
    public virtual ICollection<SOSAlert> SosalertTriggeredByUsers { get; set; } = new List<SOSAlert>();

    [InverseProperty("Caller")]
    public virtual ICollection<TripCallLog> TripCallLogCallers { get; set; } = new List<TripCallLog>();

    [InverseProperty("Receiver")]
    public virtual ICollection<TripCallLog> TripCallLogReceivers { get; set; } = new List<TripCallLog>();

    [InverseProperty("Sender")]
    public virtual ICollection<TripMessage> TripMessages { get; set; } = new List<TripMessage>();

    [InverseProperty("RecipientUser")]
    public virtual ICollection<TripShare> TripShareRecipientUsers { get; set; } = new List<TripShare>();
    [InverseProperty("SharedByUser")]
    public virtual ICollection<TripShare> TripShareSharedByUsers { get; set; } = new List<TripShare>();

    [InverseProperty("CancelledByUser")]
    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
    [InverseProperty("OwnerUser")]
    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();

    [ForeignKey("UserId")]
    [InverseProperty("Users")]
    public virtual ICollection<AppRole> Roles { get; set; } = new List<AppRole>();
}

public partial class AppRole : IdentityRole<Guid>
{
    // Thêm Description để chú thích role này làm gì (VD: "Quản trị viên hệ thống")
    public string? Description { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Roles")]
    public virtual ICollection<AppUser> Users { get; set; } = new List<AppUser>();
}
