// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[PrimaryKey("BookingId", "PromotionId")]
[Index("PromotionId", Name = "IX_BookingPromotions_PromotionId")]
public partial class BookingPromotion
{
    [Key]
    public long BookingId { get; set; }

    [Key]
    public long PromotionId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DiscountAmount { get; set; }

    [ForeignKey("BookingId")]
    [InverseProperty("BookingPromotions")]
    public virtual Booking Booking { get; set; } = null!;

    [ForeignKey("PromotionId")]
    [InverseProperty("BookingPromotions")]
    public virtual Promotion Promotion { get; set; } = null!;
}