// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;

namespace SafeRide.Domain.Entities;

public partial class BookingDriverOffer
{
    public long Id { get; set; }

    public long BookingId { get; set; }

    public Guid DriverId { get; set; }

    public DriverOfferStatus OfferStatus { get; set; } = DriverOfferStatus.Sent;

    public DateTime OfferedAt { get; set; } = DateTime.UtcNow;

    public DateTime ExpiresAt { get; set; }

    public DateTime? ConfirmedAt { get; set; }

    public DateTime? CancelledAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public virtual Booking Booking { get; set; } = null!;

    public virtual DriverProfile Driver { get; set; } = null!;
}
