// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using NetTopologySuite.Geometries;
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Booking
{
    public long BookingId { get; set; }

    public Guid CustomerId { get; set; }
    public long VehicleId { get; set; }
    public long ServiceTypeId { get; set; }

    public BookingType BookingType { get; set; } = BookingType.Now;
    public BookingStatus BookingStatus { get; set; } = BookingStatus.Searching;

    public long? PricingRuleId { get; set; }
    public long? SurgePricingRuleId { get; set; }

    public BookingSource BookingSource { get; set; } = BookingSource.Manual;

    public string PickupAddress { get; set; } = null!;
    public Point PickupLocation { get; set; } = null!;

    public string? DestinationAddress { get; set; }
    public Point? DestinationLocation { get; set; }

    public decimal? EstimatedDistanceKm { get; set; }
    public int? EstimatedDurationMinutes { get; set; }
    public decimal EstimatedFare { get; set; }
    public string? RoutePolyline { get; set; }

    public DateTime? ScheduledAt { get; set; }

    public string? SpecialRequest { get; set; }
    public Guid? CancelledBy { get; set; }
    public string? CancellationReason { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<BookingPromotion> BookingPromotions { get; set; } = new List<BookingPromotion>();

    public virtual ICollection<BookingDriverOffer> DriverOffers { get; set; } = new List<BookingDriverOffer>();

    public virtual AspNetUser? CancelledByNavigation { get; set; }

    public virtual AspNetUser Customer { get; set; } = null!;

    public virtual PricingRule? PricingRule { get; set; }

    public virtual ServiceType ServiceType { get; set; } = null!;

    public virtual SurgePricingRule? SurgePricingRule { get; set; }

    public virtual Trip? Trip { get; set; }

    public virtual Vehicle Vehicle { get; set; } = null!;
}
