// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using SafeRide.Domain.Enums;

namespace SafeRide.Domain.Entities;

[Index("BookingStatus", "CreatedAt", Name = "IX_Bookings_BookingStatus_CreatedAt", IsDescending = new[] { false, true })]
[Index("CustomerId", "BookingStatus", "CreatedAt", Name = "IX_Bookings_CustomerId_BookingStatus_CreatedAt", IsDescending = new[] { false, false, true })]
[Index("VehicleId", "BookingStatus", Name = "IX_Bookings_VehicleId_BookingStatus")]
public partial class Booking
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Customer ID is required")]
    public Guid CustomerId { get; set; }

    [Required(ErrorMessage = "Vehicle ID is required")]
    public long VehicleId { get; set; }

    [Required(ErrorMessage = "Service type ID is required")]
    public long ServiceTypeId { get; set; }

    [Required(ErrorMessage = "Booking Type is required")]
    public BookingType? BookingType { get; set; }

    [Required(ErrorMessage = "Booking Status is required")]
    public BookingStatus? BookingStatus { get; set; }

    public long? PricingRuleId { get; set; }
    public long? SurgePricingRuleId { get; set; }

    [Required(ErrorMessage = "Booking source is required")]
    public BookingSource BookingSource { get; set; } = BookingSource.Manual;

    [Required(ErrorMessage = "Pickup address is required")]
    [StringLength(255, MinimumLength = 5, ErrorMessage = "Pickup address must be between 5 and 255 characters")]
    public string PickupAddress { get; set; } = null!;

    [Required(ErrorMessage = "Pickup location is required")]
    public Point PickupLocation { get; set; } = default!;

    [StringLength(255, ErrorMessage = "Destination address cannot exceed 255 characters")]
    public string? DestinationAddress { get; set; }

    public Point DestinationLocation { get; set; } = default!;

    [Range(0.1, 9999.99, ErrorMessage = "Estimated distance must be between 0.1 and 9999.99 km")]
    [Column(TypeName = "decimal(10, 2)")]
    public decimal? EstimatedDistanceKm { get; set; }

    [Range(1, 10080, ErrorMessage = "Estimated duration must be between 1 and 10080 minutes (7 days)")]
    public int? EstimatedDurationMinutes { get; set; }

    [Range(0.01, 9999999.99, ErrorMessage = "Estimated fare must be between 0.01 and 9999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? EstimatedFare { get; set; }

    [DataType(DataType.DateTime)]
    public DateTime? ScheduledAt { get; set; }

    [StringLength(500, ErrorMessage = "Special request cannot exceed 500 characters")]
    public string? SpecialRequest { get; set; }

    public Guid? CancelledBy { get; set; }

    [StringLength(255, ErrorMessage = "Cancellation reason cannot exceed 255 characters")]
    public string? CancellationReason { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }


    [InverseProperty("Booking")]
    public virtual ICollection<BookingPromotion> BookingPromotions { get; set; } = new List<BookingPromotion>();

    [ForeignKey("CancelledBy")]
    [InverseProperty("BookingCancelledByNavigations")]
    public virtual AppUser? CancelledByNavigation { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("BookingCustomers")]
    public virtual AppUser Customer { get; set; } = null!;

    [ForeignKey("PricingRuleId")]
    [InverseProperty("Bookings")]
    public virtual PricingRule? PricingRule { get; set; }

    [ForeignKey("ServiceTypeId")]
    [InverseProperty("Bookings")]
    public virtual ServiceType ServiceType { get; set; } = null!;

    [ForeignKey("SurgePricingRuleId")]
    [InverseProperty("Bookings")]
    public virtual SurgePricingRule? SurgePricingRule { get; set; }

    [InverseProperty("Booking")]
    public virtual Trip? Trip { get; set; }

    [ForeignKey("VehicleId")]
    [InverseProperty("Bookings")]
    public virtual Vehicle Vehicle { get; set; } = null!;
}