// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class BookingPromotion
{
    public long BookingId { get; set; }

    public long PromotionId { get; set; }

    public decimal DiscountAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Booking Booking { get; set; } = null!;
    public virtual Promotion Promotion { get; set; } = null!;
}
