// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class DriverProfile
{
    public Guid DriverId { get; set; }

    public string IdentityCardNumber { get; set; } = null!;

    public int? ExperienceYears { get; set; }
    public string? HomeAddress { get; set; }

    public DriverWorkStatus WorkStatus { get; set; } = DriverWorkStatus.Offline;
    public DateTime? LastActiveAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    public virtual AspNetUser Driver { get; set; } = null!;

    public virtual ICollection<BookingDriverOffer> BookingDriverOffers { get; set; } = new List<BookingDriverOffer>();

    public virtual DriverWallet? DriverWallet { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual Trip? Trip { get; set; }
}
