// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("DriverId", Name = "UQ__DriverWa__F1B1CD059728ECFC", IsUnique = true)]
public partial class DriverWallet
{
    [Key]
    public long Id { get; set; }

    public Guid DriverId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal CurrentBalance { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("DriverWallet")]
    public virtual DriverProfile Driver { get; set; } = null!;

    [InverseProperty("Wallet")]
    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();

    [InverseProperty("Wallet")]
    public virtual ICollection<WithdrawalRequest> WithdrawalRequests { get; set; } = new List<WithdrawalRequest>();
}