// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class DriverKyc
{
    public long Id { get; set; }

    public Guid DriverId { get; set; }

    public KycDocumentType DocumentType { get; set; }
    public string? DocumentNumber { get; set; }

    public LicenseClass? LicenseClass { get; set; }

    public string? FrontImageUrl { get; set; }
    public string? BackImageUrl { get; set; }
    public string? FileUrl { get; set; }

    public DateOnly? IssueDate { get; set; }
    public DateOnly? ExpiryDate { get; set; }

    public KycStatus KycStatus { get; set; } = KycStatus.Pending;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? VerifiedAt { get; set; }
    public string? RejectionReason { get; set; }

    public virtual AspNetUser Driver { get; set; } = null!;
}
