// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;

namespace SafeRide.Domain.Entities;

[Index("LastActiveAt", Name = "IX_DriverProfiles_LastActiveAt", AllDescending = true)]
[Index("WorkStatus", Name = "IX_DriverProfiles_WorkStatus")]
[Index("IdentityCardNumber", Name = "UQ__DriverPr__59CD512142E1CF59", IsUnique = true)]
public partial class DriverProfile
{
    [Key]
    public Guid DriverId { get; set; }

    [Required(ErrorMessage = "Identity card number is required")]
    [StringLength(20, MinimumLength = 8, ErrorMessage = "Identity card number must be between 8 and 20 characters")]
    [RegularExpression("^[A-Z0-9]{8,20}$", ErrorMessage = "Identity card number must contain only alphanumeric characters")]
    [Unicode(false)]
    public string IdentityCardNumber { get; set; } = null!;

    [Range(0, 70, ErrorMessage = "Experience years must be between 0 and 70")]
    public int? ExperienceYears { get; set; }

    [StringLength(int.MaxValue, ErrorMessage = "Home address cannot exceed 500 characters")]
    [MaxLength(500)]
    public string? HomeAddress { get; set; }

    /// <summary>
    /// Vị trí thực-time của tài xế. SRID = 4326 (WGS84).
    /// Cập nhật qua SignalR / Redis, lưu DB khi cần snapshot.
    /// </summary>
    public Point? CurrentLocation { get; set; }

    [Required(ErrorMessage = "Work status is required")]
    public WorkStatus WorkStatus { get; set; } = WorkStatus.Offline;

    public DateTime? LastActiveAt { get; set; }

    // Navigation
    [ForeignKey("DriverId")]
    [InverseProperty("DriverProfile")]
    public virtual AppUser Driver { get; set; } = null!;

    [InverseProperty("Driver")]
    public virtual DriverWallet? DriverWallet { get; set; }

    [InverseProperty("Driver")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [InverseProperty("Driver")]
    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    [InverseProperty("Driver")]
    public virtual ICollection<DriverKyc> KycDocuments { get; set; } = [];
}