// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Table("DriverKyc")]
[Index("DriverId", "KycStatus", Name = "IX_DriverKyc_DriverId_KycStatus")]
[Index("KycStatus", Name = "IX_DriverKyc_KycStatus")]
[Index("LicenseNumber", Name = "UQ__DriverKy__E8890166A9AEF67E", IsUnique = true)]
public partial class DriverKyc
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Driver ID is required")]
    public Guid DriverId { get; set; }

    [Required(ErrorMessage = "Document type is required")]
    public DocumentType? DocumentType { get; set; }

    [StringLength(50, MinimumLength = 5, ErrorMessage = "License number must be between 5 and 50 characters")]
    [RegularExpression("^[A-Z0-9]{5,50}$", ErrorMessage = "License number must contain only alphanumeric characters")]
    [Unicode(false)]
    public string? LicenseNumber { get; set; }

    public LicenseClass? LicenseClass { get; set; }

    [Required(ErrorMessage = "Document URL is required")]
    [StringLength(255, MinimumLength = 10, ErrorMessage = "Document URL must be between 10 and 255 characters")]
    [Url(ErrorMessage = "Document URL must be a valid URL")]
    [Unicode(false)]
    public string DocumentUrl { get; set; } = null!;

    [Required(ErrorMessage = "Issue date is required")]
    public DateOnly IssueDate { get; set; }

    [CustomValidation(typeof(DriverKyc), nameof(ValidateExpiryDate), ErrorMessage = "Expiry date must be after issue date")]
    public DateOnly? ExpiryDate { get; set; }

    [Required(ErrorMessage = "KYC status is required")]
    public KycStatus KycStatus { get; set; } = KycStatus.Pending;

    [Required(ErrorMessage = "Created date is required")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Thời điểm admin duyệt / từ chối.</summary>
    public DateTime? VerifiedAt { get; set; }

    [StringLength(int.MaxValue, ErrorMessage = "Rejection reason cannot exceed 500 characters")]
    [MaxLength(500)]
    public string? RejectionReason { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("DriverKycs")]
    public virtual AppUser Driver { get; set; } = null!;

    // Custom validation method
    public static ValidationResult ValidateExpiryDate(DateOnly? expiryDate, ValidationContext context)
    {
        var instance = context.ObjectInstance as DriverKyc;
        if (expiryDate.HasValue && expiryDate.Value < instance?.IssueDate)
        {
            return new ValidationResult("Expiry date must be after issue date");
        }
        return ValidationResult.Success;
    }
}