// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("UserId", "IsRead", "SentAt", Name = "IX_Notifications_UserId_IsRead_SentAt", IsDescending = new[] { false, false, true })]
public partial class Notification
{
    [Key]
    public long Id { get; set; }

    public Guid UserId { get; set; }

    [StringLength(255)]
    public string Title { get; set; } = null!;

    public string Content { get; set; } = null!;

    /// <summary>e.g. "TRIP_UPDATE", "PROMOTION", "SYSTEM"</summary>
    [StringLength(50)]
    [Unicode(false)]
    public string? NotificationType { get; set; }
    public bool? IsRead { get; set; }
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
    public DateTime? ReadAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Notifications")]
    public virtual AppUser User { get; set; } = null!;
}