// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Notification
{
    public long Id { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; } = null!;
    public string Content { get; set; } = null!;
    public string? NotificationType { get; set; }

    public bool IsRead { get; set; } = false;
    public DateTime SentAt { get; set; } = DateTime.UtcNow;
    public DateTime? ReadAt { get; set; }

    public virtual AspNetUser User { get; set; } = null!;
}