// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Table("OTPVerifications")]
[Index("ExpiresAt", "IsUsed", Name = "IX_OTPVerifications_ExpiresAt_IsUsed")]
[Index("UserId", "Purpose", "IsUsed", Name = "IX_OTPVerifications_UserId_Purpose_IsUsed")]
public partial class Otpverification
{
    [Key]
    public long Id { get; set; }

    public Guid UserId { get; set; }

    /// <summary>Max 10 chars — e.g. "123456"</summary>
    [Column("OTPCode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Otpcode { get; set; } = null!;

    /// <summary>Max 50 chars — e.g. "REGISTER", "RESET_PASSWORD"</summary>
    [StringLength(50)]
    [Unicode(false)]
    public string Purpose { get; set; } = null!;

    public bool? IsUsed { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("UserId")]
    [InverseProperty("Otpverifications")]
    public virtual AppUser User { get; set; } = null!;
}