// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("PaymentStatus", "PaidAt", Name = "IX_Payments_PaymentStatus_PaidAt", IsDescending = new[] { false, true })]
[Index("TripId", "PaymentStatus", Name = "IX_Payments_TripId_PaymentStatus")]
public partial class Payment
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Trip ID is required")]
    public long TripId { get; set; }

    /// <summary>e.g. "CASH", "MOMO", "VNPAY", "ZALOPAY"</summary>
    [Required(ErrorMessage = "Payment method is required")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Payment method must be between 3 and 50 characters")]
    [RegularExpression("^[A-Z0-9_]{3,50}$", ErrorMessage = "Payment method must contain only uppercase letters, numbers, and underscores")]
    [Unicode(false)]
    public string PaymentMethod { get; set; } = null!;

    /// <summary>Mã giao dịch từ cổng thanh toán bên thứ ba.</summary>
    [StringLength(100, MinimumLength = 5, ErrorMessage = "Transaction reference must be between 5 and 100 characters")]
    [Unicode(false)]
    public string? TransactionReference { get; set; }

    [Required(ErrorMessage = "Amount is required")]
    [Range(0.01, 9999999.99, ErrorMessage = "Amount must be between 0.01 and 9999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(10, MinimumLength = 2, ErrorMessage = "Currency code must be between 2 and 10 characters")]
    [RegularExpression("^[A-Z]{3}$", ErrorMessage = "Currency code must be a 3-letter ISO 4217 code (e.g., USD, VND)")]
    [Unicode(false)]
    public string? Currency { get; set; } = "VND";

    [Required(ErrorMessage = "Payment status is required")]
    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Pending;

    public DateTime? PaidAt { get; set; }

    [ForeignKey("TripId")]
    [InverseProperty("Payments")]
    public virtual Trip Trip { get; set; } = null!;
}