// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Payment
{
    public long Id { get; set; }

    public long TripId { get; set; }

    public PaymentMethod PaymentMethod { get; set; }
    public string? TransactionReference { get; set; }

    public decimal Amount { get; set; }
    public string Currency { get; set; } = "VND";

    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Pending;

    public DateTime? PaidAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    public virtual Trip Trip { get; set; } = null!;
}