// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class PricingRule
{
    public long Id { get; set; }

    public RequiredLicenseClass VehicleClass { get; set; }

    public long ServiceTypeId { get; set; }

    public decimal BaseFare { get; set; }
    public decimal MinFare { get; set; }

    public decimal? PricePerKm { get; set; }
    public decimal? PricePerHour { get; set; }

    public bool IsActive { get; set; } = true;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ServiceType ServiceType { get; set; } = null!;
}