// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("VehicleClass", "ServiceTypeId", "IsActive", Name = "IX_PricingRules_VehicleClass_ServiceTypeId_IsActive")]
public partial class PricingRule
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Vehicle license class is required")]
    public VehicleClass VehicleClass { get; set; }

    public long ServiceTypeId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal BaseFare { get; set; }
    [Column(TypeName = "decimal(18, 2)")]
    public decimal MinFare { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PricePerKm { get; set; }
    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PricePerHour { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("PricingRule")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("ServiceTypeId")]
    [InverseProperty("PricingRules")]
    public virtual ServiceType ServiceType { get; set; } = null!;
}