// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;

namespace SafeRide.Domain.Entities;

[Index("IsActive", "EndDate", Name = "IX_Promotions_IsActive_EndDate")]
[Index("PromotionCode", Name = "UQ__Promotio__A617E4B608DA0B31", IsUnique = true)]
public partial class Promotion
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Promotion code is required")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "Promotion code must be between 3 and 50 characters")]
    [RegularExpression("^[A-Z0-9_-]{3,50}$", ErrorMessage = "Promotion code must contain only uppercase letters, numbers, hyphens, and underscores")]
    [Unicode(false)]
    public string PromotionCode { get; set; } = null!;

    [Required(ErrorMessage = "Discount Type is required")]
    public DiscountType? DiscountType { get; set; }

    [Required(ErrorMessage = "Discount value is required")]
    [Range(0.01, 999999.99, ErrorMessage = "Discount value must be between 0.01 and 999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal DiscountValue { get; set; }

    [Required(ErrorMessage = "Start date is required")]
    [DataType(DataType.DateTime)]
    public DateTime StartDate { get; set; }

    [Required(ErrorMessage = "End date is required")]
    [DataType(DataType.DateTime)]
    [CustomValidation(typeof(Promotion), nameof(ValidateEndDate), ErrorMessage = "End date must be after start date")]
    public DateTime EndDate { get; set; }

    /// <summary>Tổng giới hạn lượt dùng mã trên toàn hệ thống.</summary>
    [Required(ErrorMessage = "Maximum usage count is required")]
    [Range(1, 1000000, ErrorMessage = "Maximum usage count must be between 1 and 1,000,000")]
    public int MaxUsageCount { get; set; }

    /// <summary>Số lượt thực tế đã dùng — tăng dần, có thể dùng optimistic concurrency.</summary>
    [Required(ErrorMessage = "Current usage count is required")]
    [Range(0, int.MaxValue, ErrorMessage = "Current usage count cannot be negative")]
    public int CurrentUsageCount { get; set; }

    [Required(ErrorMessage = "Minimum order value is required")]
    [Range(0, 999999.99, ErrorMessage = "Minimum order value must be between 0 and 999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal MinimumOrderValue { get; set; }

    [Required(ErrorMessage = "Maximum discount value is required")]
    [Range(0.01, 999999.99, ErrorMessage = "Maximum discount value must be between 0.01 and 999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal MaximumDiscountValue { get; set; }

    [Required(ErrorMessage = "Usage limit per user is required")]
    [Range(1, 100, ErrorMessage = "Usage limit per user must be between 1 and 100")]
    public int UsageLimitPerUser { get; set; }

    [Required(ErrorMessage = "Active status is required")]
    public bool IsActive { get; set; } = true;

    [InverseProperty("Promotion")]
    public virtual ICollection<BookingPromotion> BookingPromotions { get; set; } = new List<BookingPromotion>();

    // Custom validation method
    public static ValidationResult ValidateEndDate(DateTime endDate, ValidationContext context)
    {
        var instance = context.ObjectInstance as Promotion;
        if (endDate <= instance?.StartDate)
        {
            return new ValidationResult("End date must be after start date");
        }
        return ValidationResult.Success;
    }
}