// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Promotion
{
    public long Id { get; set; }

    public string PromotionCode { get; set; } = null!;

    public DiscountType? DiscountType { get; set; }
    public decimal DiscountValue { get; set; }

    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }

    public int MaxUsageCount { get; set; } = 100;

    public int CurrentUsageCount { get; set; } = 0;
    public decimal MinimumOrderValue { get; set; } = 0;
    public decimal MaximumDiscountValue { get; set; } = 0;
    public int UsageLimitPerUser { get; set; } = 1;

    public bool IsActive { get; set; } = true;

    public virtual ICollection<BookingPromotion> BookingPromotions { get; set; } = new List<BookingPromotion>();
}