// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("CustomerId", "CreatedAt", Name = "IX_Ratings_CustomerId_CreatedAt", IsDescending = new[] { false, true })]
[Index("DriverId", "RatingScore", Name = "IX_Ratings_DriverId_RatingScore")]
[Index("TripId", Name = "UQ__Ratings__51DC713F6F452792", IsUnique = true)]
public partial class Rating
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Trip ID is required")]
    [Range(1, long.MaxValue, ErrorMessage = "Trip ID must be greater than 0")]
    public long TripId { get; set; }

    [Required(ErrorMessage = "Customer ID is required")]
    public Guid CustomerId { get; set; }

    [Required(ErrorMessage = "Driver ID is required")]
    public Guid DriverId { get; set; }

    [Required(ErrorMessage = "Rating score is required")]
    [Range(1, 5, ErrorMessage = "Rating score must be between 1 and 5")]
    public int RatingScore { get; set; }

    [StringLength(1000, MinimumLength = 3, ErrorMessage = "Comment must be between 3 and 1000 characters")]
    public string? Comment { get; set; }

    [Required(ErrorMessage = "Created date is required")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("CustomerId")]
    [InverseProperty("Ratings")]
    public virtual AppUser Customer { get; set; } = null!;

    [ForeignKey("DriverId")]
    [InverseProperty("Ratings")]
    public virtual DriverProfile Driver { get; set; } = null!;

    [ForeignKey("TripId")]
    [InverseProperty("Rating")]
    public virtual Trip Trip { get; set; } = null!;
}