// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Rating
{
    public long Id { get; set; }

    public long TripId { get; set; }
    public Guid CustomerId { get; set; }
    public Guid DriverId { get; set; }

    public int RatingScore { get; set; }
    public string? Comment { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual AspNetUser Customer { get; set; } = null!;

    public virtual DriverProfile Driver { get; set; } = null!;

    public virtual Trip Trip { get; set; } = null!;
}