// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class RefreshToken
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }
    public Guid SessionId { get; set; }

    public byte[] TokenHash { get; set; } = Array.Empty<byte>();
    public string? JwtId { get; set; }

    public string? DeviceId { get; set; }
    public string? DeviceName { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAt { get; set; }
    public DateTime? RevokedAt { get; set; }

    public byte[]? ReplacedByTokenHash { get; set; }

    /// <summary>
    /// Computed column trong SQL.
    /// Không nên set trực tiếp từ code.
    /// </summary>
    public int IsRevoked { get; set; }

    public virtual AspNetUser User { get; set; } = null!;
}
