// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("Status", "CreatedAt", Name = "IX_Reports_Status_CreatedAt", IsDescending = new[] { false, true })]
[Index("UserId", "CreatedAt", Name = "IX_Reports_UserId_CreatedAt", IsDescending = new[] { false, true })]
public partial class Report
{
    [Key]
    public long Id { get; set; }

    public long? TripId { get; set; }

    public Guid UserId { get; set; }

    [StringLength(255)]
    public string Subject { get; set; } = null!;
    public string Description { get; set; } = null!;

    public ReportStatus Status { get; set; } = ReportStatus.Pending;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("TripId")]
    [InverseProperty("Reports")]
    public virtual Trip? Trip { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Reports")]
    public virtual AppUser User { get; set; } = null!;
}