// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Report
{
    public long Id { get; set; }

    public long? TripId { get; set; }
    public Guid UserId { get; set; }

    public string Subject { get; set; } = null!;

    public string Description { get; set; } = null!;

    public ReportStatus Status { get; set; } = ReportStatus.Pending;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual Trip? Trip { get; set; }
    public virtual AspNetUser User { get; set; } = null!;
}