// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace SafeRide.Domain.Entities;

public partial class RouteDeviation
{
    public long Id { get; set; }

    public long TripId { get; set; }

    public Point Location { get; set; } = null!;

    public int DistanceDeviationMeters { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual Trip Trip { get; set; } = null!;
}