// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using NetTopologySuite.Geometries;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("TripId", "CreatedAt", Name = "IX_RouteDeviations_TripId_CreatedAt", IsDescending = new[] { false, true })]
public partial class RouteDeviation
{
    [Key]
    public long Id { get; set; }

    public long TripId { get; set; }
    /// <summary>Toạ độ tại thời điểm phát hiện lệch — SRID 4326.</summary>
    public Point Location { get; set; } = default!;

    public int DistanceDeviationMeters { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("TripId")]
    [InverseProperty("RouteDeviations")]
    public virtual Trip Trip { get; set; } = null!;
}