// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("ServiceName", Name = "UQ__ServiceT__A42B5F993C233A5F", IsUnique = true)]
public partial class ServiceType
{
    [Key]
    public long Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ServiceName { get; set; } = null!;

    [InverseProperty("ServiceType")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("ServiceType")]
    public virtual ICollection<PricingRule> PricingRules { get; set; } = new List<PricingRule>();
}