// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class ServiceType
{
    public long Id { get; set; }

    public string ServiceName { get; set; } = null!;

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<PricingRule> PricingRules { get; set; } = new List<PricingRule>();
}