// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using NetTopologySuite.Geometries;
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class SOSAlert
{
    public long Id { get; set; }

    public long TripId { get; set; }
    public Guid TriggeredByUserId { get; set; }

    public Point Location { get; set; } = null!;
    public string? EmergencyMessage { get; set; }

    public SOSStatus SOSStatus { get; set; } = SOSStatus.Active;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public Guid? ResolvedByUserId { get; set; }
    public DateTime? ResolvedAt { get; set; }

    public virtual AspNetUser? ResolvedByUser { get; set; }
    public virtual AspNetUser TriggeredByUser { get; set; } = null!;
    public virtual Trip Trip { get; set; } = null!;
}