// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using NetTopologySuite.Geometries;

namespace SafeRide.Domain.Entities;

[Table("SOSAlerts")]
[Index("TripId", Name = "IX_SOSAlerts_TripId")]
public partial class SOSAlert
{
    [Key]
    public long Id { get; set; }

    public long TripId { get; set; }
    public Guid TriggeredByUserId { get; set; }

    /// <summary>Toạ độ lúc kích hoạt SOS — SRID 4326.</summary>
    public Point Location { get; set; } = default!;

    [StringLength(500)]
    public string? EmergencyMessage { get; set; }

    [Column("SOSStatus")]
    [Unicode(false)]
    public SOSAlertStatus SOSStatus { get; set; } = SOSAlertStatus.Active;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public Guid? ResolvedByUserId { get; set; }
    public DateTime? ResolvedAt { get; set; }


    [ForeignKey("ResolvedByUserId")]
    [InverseProperty("SosalertResolvedByUsers")]
    public virtual AppUser? ResolvedByUser { get; set; }

    [ForeignKey("TriggeredByUserId")]
    [InverseProperty("SosalertTriggeredByUsers")]
    public virtual AppUser TriggeredByUser { get; set; } = default!;

    [ForeignKey("TripId")]
    [InverseProperty("Sosalerts")]
    public virtual Trip Trip { get; set; } = default!;
}