// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("IsActive", Name = "IX_SurgePricingRules_IsActive")]
public partial class SurgePricingRule
{
    [Key]
    public long Id { get; set; }

    [StringLength(100)]
    public string RuleName { get; set; } = null!;

    public TimeOnly StartTime { get; set; }
    public TimeOnly EndTime { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AppliedDays { get; set; } = null!;

    [Column(TypeName = "decimal(3, 2)")]
    public decimal SurgeMultiplier { get; set; } = 1.00m;

    public bool IsActive { get; set; } = true;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("SurgePricingRule")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}