// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class SystemSetting
{
    public long Id { get; set; }

    public string SettingKey { get; set; } = null!;
    public string? SettingValue { get; set; }

    public string? Description { get; set; }
}