// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("TripId", "SentAt", Name = "IX_TripMessages_TripId_SentAt", IsDescending = new[] { false, true })]
public partial class TripMessage
{
    [Key]
    public long Id { get; set; }

    public long TripId { get; set; }

    public Guid SenderId { get; set; }

    [StringLength(1000)]
    public string Content { get; set; } = null!;

    public DateTime SentAt { get; set; } = DateTime.UtcNow;

    public bool IsRead { get; set; }

    [ForeignKey("SenderId")]
    [InverseProperty("TripMessages")]
    public virtual AppUser Sender { get; set; } = null!;

    [ForeignKey("TripId")]
    [InverseProperty("TripMessages")]
    public virtual Trip Trip { get; set; } = null!;
}