// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SafeRide.Domain.Entities;

[Index("TripId", "ExpiresAt", Name = "IX_TripShares_TripId_ExpiresAt")]
[Index("ShareToken", Name = "UQ__TripShar__9F895CDCE0F255B9", IsUnique = true)]
public partial class TripShare
{
    [Key]
    public long Id { get; set; }

    public long TripId { get; set; }

    public Guid SharedByUserId { get; set; }
    public Guid RecipientUserId { get; set; }

    /// <summary>Token ngẫu nhiên an toàn — dùng để tạo link chia sẻ public.</summary>
    [StringLength(100)]
    [Unicode(false)]
    public string ShareToken { get; set; } = null!;

    public DateTime ExpiresAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("RecipientUserId")]
    [InverseProperty("TripShareRecipientUsers")]
    public virtual AppUser RecipientUser { get; set; } = null!;

    [ForeignKey("SharedByUserId")]
    [InverseProperty("TripShareSharedByUsers")]
    public virtual AppUser SharedByUser { get; set; } = null!;

    [ForeignKey("TripId")]
    [InverseProperty("TripShares")]
    public virtual Trip Trip { get; set; } = null!;
}