// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("DriverId", "TripStatus", "CreatedAt", Name = "IX_Trips_DriverId_TripStatus_CreatedAt", IsDescending = new[] { false, false, true })]
[Index("TripStatus", "CreatedAt", Name = "IX_Trips_TripStatus_CreatedAt", IsDescending = new[] { false, true })]
[Index("BookingId", Name = "UQ__Trips__73951AEC460777C9", IsUnique = true)]
public partial class Trip
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Booking ID is required")]
    public long BookingId { get; set; }

    [Required(ErrorMessage = "Driver ID is required")]
    public Guid DriverId { get; set; }

    public TripStatus TripStatus { get; set; } = TripStatus.ACCEPTED;

    public DateTime? DriverAssignedAt { get; set; }
    public DateTime? ArrivedAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    /// <summary>Encoded polyline của lộ trình thực tế — lưu khi trip COMPLETED.</summary>
    [StringLength(int.MaxValue, ErrorMessage = "Route polyline cannot exceed maximum length")]
    [MaxLength(10000)]
    public string? RoutePolyline { get; set; }

    /// <summary>True khi nút SOS được kích hoạt trong chuyến đi.</summary>
    [Column("IsSOSActivated")]
    [Required(ErrorMessage = "SOS activation flag is required")]
    public bool? IsSOSActivated { get; set; } = false;

    public Guid? CancelledByUserId { get; set; }

    [StringLength(255, ErrorMessage = "Cancellation reason cannot exceed 255 characters")]
    public string? CancellationReason { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    [ForeignKey("BookingId")]
    [InverseProperty("Trip")]
    public virtual Booking Booking { get; set; } = default!;

    [ForeignKey("CancelledByUserId")]
    [InverseProperty("Trips")]
    public virtual AppUser? CancelledByUser { get; set; }

    [ForeignKey("DriverId")]
    [InverseProperty("Trips")]
    public virtual DriverProfile Driver { get; set; } = default!;

    [InverseProperty("Trip")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Trip")]
    public virtual Rating? Rating { get; set; }

    [InverseProperty("Trip")]
    public virtual ICollection<RouteDeviation> RouteDeviations { get; set; } = new List<RouteDeviation>();

    [InverseProperty("Trip")]
    public virtual ICollection<SOSAlert> SOSAlerts { get; set; } = new List<SOSAlert>();

    [InverseProperty("Trip")]
    public virtual ICollection<TripCallLog> TripCallLogs { get; set; } = new List<TripCallLog>();

    [InverseProperty("Trip")]
    public virtual ICollection<TripMessage> TripMessages { get; set; } = new List<TripMessage>();

    [InverseProperty("Trip")]
    public virtual ICollection<TripShare> TripShares { get; set; } = new List<TripShare>();

    [InverseProperty("Trip")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("Trip")]
    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}