// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("TripId", "StartedAt", Name = "IX_TripCallLogs_TripId_StartedAt", IsDescending = new[] { false, true })]
public partial class TripCallLog
{
    [Key]
    public long Id { get; set; }

    public long TripId { get; set; }
    public Guid CallerId { get; set; }
    public Guid ReceiverId { get; set; }

    public int? DurationSeconds { get; set; }

    [StringLength(20)]
    public CallStatus CallStatus { get; set; }
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("CallerId")]
    [InverseProperty("TripCallLogCallers")]
    public virtual AppUser Caller { get; set; } = null!;

    [ForeignKey("ReceiverId")]
    [InverseProperty("TripCallLogReceivers")]
    public virtual AppUser Receiver { get; set; } = null!;

    [ForeignKey("TripId")]
    [InverseProperty("TripCallLogs")]
    public virtual Trip Trip { get; set; } = null!;
}