// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Trip
{
    public long Id { get; set; }

    public long BookingId { get; set; }
    public Guid DriverId { get; set; }

    public TripStatus TripStatus { get; set; } = TripStatus.ACCEPTED;

    public DateTime? DriverAssignedAt { get; set; }
    public DateTime? ArrivedAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? EndedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    public decimal? ActualDistanceKm { get; set; }
    public int? ActualDurationMinutes { get; set; }

    public decimal? ActualFare { get; set; }
    public decimal? FinalFare { get; set; }

    public string? RoutePolyline { get; set; }

    public bool IsSOSActivated { get; set; } = false;

    public Guid? CancelledByUserId { get; set; }
    public string? CancellationReason { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual Booking Booking { get; set; } = null!;

    public virtual AspNetUser? CancelledByUser { get; set; }

    public virtual DriverProfile Driver { get; set; } = null!;

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Rating? Rating { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual ICollection<RouteDeviation> RouteDeviations { get; set; } = new List<RouteDeviation>();

    public virtual ICollection<SOSAlert> SOSAlerts { get; set; } = new List<SOSAlert>();

    public virtual ICollection<TripShare> TripShares { get; set; } = new List<TripShare>();

    public virtual ICollection<TripReturnConfirmation> ReturnConfirmations { get; set; } = new List<TripReturnConfirmation>();

    public virtual ICollection<WalletTransaction> WalletTransactions { get; set; } = new List<WalletTransaction>();
}
