// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class TripShare
{
    public long Id { get; set; }

    public long TripId { get; set; }

    public Guid SharedByUserId { get; set; }
    public Guid RecipientUserId { get; set; }

    public string ShareToken { get; set; } = null!;

    public DateTime ExpiresAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual AspNetUser RecipientUser { get; set; } = null!;
    public virtual AspNetUser SharedByUser { get; set; } = null!;
    public virtual Trip Trip { get; set; } = null!;
}