// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class Vehicle
{
    public long Id { get; set; }

    public Guid OwnerUserId { get; set; }

    public string PlateNumber { get; set; } = null!;

    public string BrandModel { get; set; } = null!;

    public RequiredLicenseClass RequiredLicenseClass { get; set; }
    public VehicleType VehicleType { get; set; }
    public EngineType EngineType { get; set; }
    public TransmissionType TransmissionType { get; set; }

    public string? Color { get; set; }

    public bool IsDeleted { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual AspNetUser OwnerUser { get; set; } = null!;
}