// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("OwnerUserId", "IsDeleted", Name = "IX_Vehicles_OwnerUserId_IsDeleted")]
[Index("PlateNumber", Name = "UQ__Vehicles__03692624959587B0", IsUnique = true)]
public partial class Vehicle
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Owner user ID is required")]
    public Guid OwnerUserId { get; set; }

    /// <summary>Biển số xe — unique trong hệ thống.</summary>
    [Required(ErrorMessage = "License plate number is required")]
    [StringLength(20, MinimumLength = 5, ErrorMessage = "License plate must be between 5 and 20 characters")]
    [RegularExpression("^[A-Z0-9-]{5,20}$", ErrorMessage = "License plate must contain only alphanumeric characters and hyphens")]
    [Unicode(false)]
    public string PlateNumber { get; set; } = null!;

    /// <summary>Hãng xe + model, e.g. "Honda Wave 110i".</summary>
    [Required(ErrorMessage = "Vehicle brand and model is required")]
    [StringLength(100, MinimumLength = 5, ErrorMessage = "Brand and model must be between 5 and 100 characters")]
    public string BrandModel { get; set; } = null!;

    [Required(ErrorMessage = "Vehicle license class is required")]
    public VehicleClass RequiredLicenseClass { get; set; }

    [Required(ErrorMessage = "Engine type is required")]
    public EngineType EngineType { get; set; }

    [Required(ErrorMessage = "Transmission type is required")]
    public TransmissionType TransmissionType { get; set; }

    [StringLength(30, MinimumLength = 2, ErrorMessage = "Color must be between 2 and 30 characters")]
    public string? Color { get; set; }

    [Required(ErrorMessage = "IsDeleted flag is required")]
    public bool? IsDeleted { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [InverseProperty("Vehicle")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("OwnerUserId")]
    [InverseProperty("Vehicles")]
    public virtual AppUser OwnerUser { get; set; } = null!;
}