// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class WalletTransaction
{
    public long Id { get; set; }

    public long WalletId { get; set; }
    public long? TripId { get; set; }

    public WalletTransactionType TransactionType { get; set; }

    public decimal Amount { get; set; }
    public string? Description { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual Trip? Trip { get; set; }
    public virtual DriverWallet Wallet { get; set; } = null!;
}