// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("WalletId", "CreatedAt", Name = "IX_WalletTransactions_WalletId_CreatedAt", IsDescending = new[] { false, true })]
[Index("WalletId", "TransactionType", Name = "IX_WalletTransactions_WalletId_TransactionType")]
public partial class WalletTransaction
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Wallet ID is required")]
    [Range(1, long.MaxValue, ErrorMessage = "Wallet ID must be greater than 0")]
    public long WalletId { get; set; }

    public long? TripId { get; set; }

    [Required(ErrorMessage = "Transaction type is required")]
    public TransactionType TransactionType { get; set; }

    [Required(ErrorMessage = "Amount is required")]
    [Range(0.01, 9999999.99, ErrorMessage = "Amount must be between 0.01 and 9999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters")]
    public string? Description { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey("TripId")]
    [InverseProperty("WalletTransactions")]
    public virtual Trip? Trip { get; set; }

    [ForeignKey("WalletId")]
    [InverseProperty("WalletTransactions")]
    public virtual DriverWallet Wallet { get; set; } = null!;
}