// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SafeRide.Domain.Entities;

[Index("Status", "CreatedAt", Name = "IX_WithdrawalRequests_Status_CreatedAt", IsDescending = new[] { false, true })]
[Index("WalletId", "Status", Name = "IX_WithdrawalRequests_WalletId_Status")]
public partial class WithdrawalRequest
{
    [Key]
    public long Id { get; set; }

    [Required(ErrorMessage = "Wallet ID is required")]
    public long WalletId { get; set; }

    [Required(ErrorMessage = "Withdrawal amount is required")]
    [Range(0.01, 9999999.99, ErrorMessage = "Withdrawal amount must be between 0.01 and 9999999.99")]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Required(ErrorMessage = "Bank name is required")]
    [StringLength(100, MinimumLength = 2, ErrorMessage = "Bank name must be between 2 and 100 characters")]
    public string BankName { get; set; } = null!;

    [Required(ErrorMessage = "Bank account number is required")]
    [StringLength(50, MinimumLength = 5, ErrorMessage = "Bank account number must be between 5 and 50 characters")]
    [RegularExpression("^[A-Z0-9]{5,50}$", ErrorMessage = "Bank account number must contain only alphanumeric characters")]
    [Unicode(false)]
    public string BankAccountNumber { get; set; } = null!;

    [Required(ErrorMessage = "Bank account name is required")]
    [StringLength(150, MinimumLength = 2, ErrorMessage = "Bank account name must be between 2 and 150 characters")]
    public string BankAccountName { get; set; } = null!;

    [Required(ErrorMessage = "Status is required")]
    public WithdrawalStatus Status { get; set; } = WithdrawalStatus.Pending;

    [StringLength(255, ErrorMessage = "Rejection reason cannot exceed 255 characters")]
    public string? RejectionReason { get; set; }

    [Required(ErrorMessage = "Created date is required")]
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? ProcessedAt { get; set; }

    [ForeignKey("WalletId")]
    [InverseProperty("WithdrawalRequests")]
    public virtual DriverWallet Wallet { get; set; } = null!;
}