// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using SafeRide.Domain.Enums;
using System;
using System.Collections.Generic;

namespace SafeRide.Domain.Entities;

public partial class WithdrawalRequest
{
    public long Id { get; set; }

    public long WalletId { get; set; }

    public decimal Amount { get; set; }

    public string BankName { get; set; } = null!;
    public string BankAccountNumber { get; set; } = null!;
    public string BankAccountName { get; set; } = null!;

    public WithdrawalRequestStatus Status { get; set; } = WithdrawalRequestStatus.Pending;
    public string? RejectionReason { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ProcessedAt { get; set; }

    public virtual DriverWallet Wallet { get; set; } = null!;
}