﻿// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using SafeRide.Domain.Entities;
using SafeRide.Domain.Enums;

namespace SafeRide.Infrastructure.Persistence;

public partial class ApplicationDbContext : IdentityDbContext<AspNetUser, AspNetRole, Guid>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingPromotion> BookingPromotions { get; set; }

    public virtual DbSet<DriverKyc> DriverKycs { get; set; }

    public virtual DbSet<DriverProfile> DriverProfiles { get; set; }

    public virtual DbSet<DriverWallet> DriverWallets { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PricingRule> PricingRules { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<RouteDeviation> RouteDeviations { get; set; }

    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

    public virtual DbSet<SOSAlert> Sosalerts { get; set; }

    public virtual DbSet<SurgePricingRule> SurgePricingRules { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripShare> TripShares { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

    public virtual DbSet<WithdrawalRequest> WithdrawalRequests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<AspNetRole>(entity =>
        {

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {



            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AvatarUrl).HasMaxLength(500);
            entity.Property(e => e.BanReason).HasMaxLength(500);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.FullName).HasMaxLength(250);
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<IdentityUserRole<Guid>>(
                    r => r.HasOne<AspNetRole>().WithMany()
                        .HasForeignKey(ur => ur.RoleId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_Roles"),
                    l => l.HasOne<AspNetUser>().WithMany()
                        .HasForeignKey(ur => ur.UserId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_Users"),
                    j =>
                    {
                        j.HasKey(ur => new { ur.UserId, ur.RoleId });
                        j.ToTable("AspNetUserRoles");
                    });
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bookings__3214EC073A8063CD");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Bookings_BookingType", "[BookingType] IN ('Now', 'Scheduled')");
                tb.HasCheckConstraint("CK_Bookings_BookingStatus", "[BookingStatus] IN ('SEARCHING_DRIVER', 'DRIVER_ASSIGNED', 'CUSTOMER_CANCELLED', 'DRIVER_CANCELLED', 'EXPIRED', 'CONVERTED_TO_TRIP')");
                tb.HasCheckConstraint("CK_Bookings_BookingSource", "[BookingSource] IN ('Manual', 'VoiceCommand', 'Scheduled')");
                tb.HasCheckConstraint("CK_Bookings_EstimatedDistanceKm", "[EstimatedDistanceKm] IS NULL OR [EstimatedDistanceKm] >= 0");
                tb.HasCheckConstraint("CK_Bookings_EstimatedDurationMinutes", "[EstimatedDurationMinutes] IS NULL OR [EstimatedDurationMinutes] >= 0");
                tb.HasCheckConstraint("CK_Bookings_EstimatedFare", "[EstimatedFare] IS NULL OR [EstimatedFare] >= 0");
                tb.HasCheckConstraint("CK_Bookings_PickupLocation", "[PickupLocation].STSrid = 4326");
                tb.HasCheckConstraint("CK_Bookings_DestinationLocation", "[DestinationLocation] IS NULL OR [DestinationLocation].STSrid = 4326");
                tb.HasCheckConstraint("CK_Bookings_ScheduledAt", "([BookingType] = 'Now' AND [ScheduledAt] IS NULL) OR ([BookingType] = 'Scheduled' AND [ScheduledAt] IS NOT NULL)");
            });



            entity.Property(e => e.BookingSource)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValue(BookingSource.Manual);
            entity.Property(e => e.BookingStatus)
                .HasConversion<string>()
                .HasMaxLength(30)
                .HasDefaultValueSql("('SEARCHING_DRIVER')");
            entity.Property(e => e.BookingType)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Now')");
            entity.Property(e => e.CancellationReason).HasMaxLength(255);
            entity.Property(e => e.DestinationAddress).HasMaxLength(255);
            entity.Property(e => e.EstimatedDistanceKm).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.EstimatedFare).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PickupAddress).HasMaxLength(255);
            entity.Property(e => e.SpecialRequest).HasMaxLength(500);

            entity.HasOne(d => d.CancelledByNavigation).WithMany(p => p.BookingCancelledByNavigations)
                .HasForeignKey(d => d.CancelledBy)
                .HasConstraintName("FK_Bookings_CancelledBy");

            entity.HasOne(d => d.Customer).WithMany(p => p.BookingCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_AspNetUsers");

            entity.HasOne(d => d.PricingRule).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.PricingRuleId)
                .HasConstraintName("FK_Bookings_PricingRule");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_ServiceType");

            entity.HasOne(d => d.SurgePricingRule).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.SurgePricingRuleId)
                .HasConstraintName("FK_Bookings_SurgeRule");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.VehicleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Vehicle");
        });

        modelBuilder.Entity<BookingPromotion>(entity =>
        {
            entity.HasKey(e => new { e.BookingId, e.PromotionId }).HasName("PK__BookingP__96B958114224E6FD");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_BookingPromotions_DiscountAmount", "[DiscountAmount] >= 0");
            });


            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPromotions)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPromotion_Booking");

            entity.HasOne(d => d.Promotion).WithMany(p => p.BookingPromotions)
                .HasForeignKey(d => d.PromotionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPromotion_Promotion");
        });

        modelBuilder.Entity<DriverKyc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DriverKy__3214EC075745B3C5");

            entity.ToTable("DriverKyc", tb =>
            {
                tb.HasCheckConstraint("CK_DriverKyc_DocumentType", "[DocumentType] IN ('ID_CARD', 'DRIVING_LICENSE', 'CRIMINAL_RECORD')");
                tb.HasCheckConstraint("CK_DriverKyc_LicenseClass", "[LicenseClass] IS NULL OR [LicenseClass] IN ('A1', 'A', 'B1', 'B', 'C1', 'C', 'D1', 'D2', 'D', 'Old_B1', 'Old_B2', 'Old_A1', 'Old_A2')");
                tb.HasCheckConstraint("CK_DriverKyc_KycStatus", "[KycStatus] IN ('Pending', 'Approved', 'Rejected')");
                tb.HasCheckConstraint("CK_DriverKyc_DocumentFile", "[FrontImageUrl] IS NOT NULL OR [BackImageUrl] IS NOT NULL OR [FileUrl] IS NOT NULL");
                tb.HasCheckConstraint("CK_DriverKyc_DrivingLicense", "[DocumentType] <> 'DRIVING_LICENSE' OR ([DocumentNumber] IS NOT NULL AND [LicenseClass] IS NOT NULL)");
            });



            entity.Property(e => e.BackImageUrl).HasMaxLength(500);
            entity.Property(e => e.DocumentNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DocumentType)
                .HasConversion<string>()
                .HasMaxLength(50);
            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.FrontImageUrl).HasMaxLength(500);
            entity.Property(e => e.KycStatus)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Pending')");
            entity.Property(e => e.LicenseClass)
                .HasConversion<string>()
                .HasMaxLength(10);

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverKycs)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DriverKyc_AspNetUsers");
        });

        modelBuilder.Entity<DriverProfile>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__DriverPr__F1B1CD046AA3E9C5");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_DriverProfiles_WorkStatus", "[WorkStatus] IN ('Online', 'Offline', 'Busy')");
                tb.HasCheckConstraint("CK_DriverProfiles_ExperienceYears", "[ExperienceYears] IS NULL OR [ExperienceYears] >= 0");
            });



            // Prevent EF Core from creating a wrong shadow FK DriverProfiles.TripId.
            // DriverProfile has many historical Trips through Trips.DriverId.
            entity.Ignore(e => e.Trip);

            entity.Property(e => e.DriverId).ValueGeneratedNever();
            entity.Property(e => e.ExperienceYears).HasDefaultValue(0);
            entity.Property(e => e.IdentityCardNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.WorkStatus)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Offline')");


            entity.HasOne(d => d.Driver).WithOne(p => p.DriverProfile)
                .HasForeignKey<DriverProfile>(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DriverProfiles_AspNetUsers");
        });

        modelBuilder.Entity<DriverWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DriverWa__3214EC0723702C3C");


            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_DriverWallets_CurrentBalance", "[CurrentBalance] >= 0");
            });

            entity.Property(e => e.CurrentBalance)
                .HasColumnType("decimal(18, 2)")
                .HasDefaultValue(0m);

            entity.HasOne(d => d.Driver).WithOne(p => p.DriverWallet)
                .HasForeignKey<DriverWallet>(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wallet_Driver");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifica__3214EC07BC6B781B");


            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.NotificationType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_AspNetUsers");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC076511D9DA");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Payments_PaymentMethod", "[PaymentMethod] IN ('QR', 'CASH')");
                tb.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");
                tb.HasCheckConstraint("CK_Payments_PaymentStatus", "[PaymentStatus] IN ('Pending', 'Success', 'Failed', 'Cancelled')");
                tb.HasCheckConstraint("CK_Payments_TransactionReference", "([PaymentMethod] = 'QR' AND [TransactionReference] IS NOT NULL) OR ([PaymentMethod] = 'CASH' AND [TransactionReference] IS NULL)");
            });


            entity.Property(e => e.Currency)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValue("VND");
            entity.Property(e => e.PaymentMethod)
                .HasConversion<string>()
                .HasMaxLength(20);
            entity.Property(e => e.PaymentStatus)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Pending')");
            entity.Property(e => e.TransactionReference)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Trip).WithMany(p => p.Payments)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Trips");
        });

        modelBuilder.Entity<PricingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PricingR__3214EC07CFB6D6FF");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_PricingRules_VehicleClass", "[VehicleClass] IN ('A1', 'A', 'B', 'C1', 'C', 'D1', 'D2', 'D')");
                tb.HasCheckConstraint("CK_PricingRules_BaseFare", "[BaseFare] >= 0");
                tb.HasCheckConstraint("CK_PricingRules_MinFare", "[MinFare] >= 0");
                tb.HasCheckConstraint("CK_PricingRules_PricePerKm", "[PricePerKm] IS NULL OR [PricePerKm] >= 0");
                tb.HasCheckConstraint("CK_PricingRules_PricePerHour", "[PricePerHour] IS NULL OR [PricePerHour] >= 0");
            });

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MinFare).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PricePerHour).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PricePerKm).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.VehicleClass)
                .HasConversion<string>()
                .HasMaxLength(10);

            entity.HasOne(d => d.ServiceType).WithMany(p => p.PricingRules)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PricingRules_ServiceType");
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Promotio__3214EC07CE4C05F3");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Promotions_DiscountType", "[DiscountType] IS NULL OR [DiscountType] IN ('Percentage', 'Fixed')");
                tb.HasCheckConstraint("CK_Promotions_Date", "[EndDate] > [StartDate]");
                tb.HasCheckConstraint("CK_Promotions_DiscountValue", "[DiscountValue] > 0");
                tb.HasCheckConstraint("CK_Promotions_Usage", "[MaxUsageCount] > 0 AND [CurrentUsageCount] >= 0 AND [CurrentUsageCount] <= [MaxUsageCount] AND [UsageLimitPerUser] > 0");
                tb.HasCheckConstraint("CK_Promotions_OrderValue", "[MinimumOrderValue] >= 0 AND [MaximumDiscountValue] >= 0");
            });


            entity.Property(e => e.DiscountType)
                .HasConversion<string>()
                .HasMaxLength(20);
            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxUsageCount).HasDefaultValue(100);
            entity.Property(e => e.MaximumDiscountValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MinimumOrderValue).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PromotionCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UsageLimitPerUser).HasDefaultValue(1);
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ratings__3214EC07E3A4C19E");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Ratings_RatingScore", "[RatingScore] BETWEEN 1 AND 5");
                tb.HasCheckConstraint("CK_Ratings_Customer_Driver", "[CustomerId] <> [DriverId]");
            });



            entity.Property(e => e.Comment).HasMaxLength(1000);

            entity.HasOne(d => d.Customer).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_Customers");

            entity.HasOne(d => d.Driver).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_DriverProfiles");

            entity.HasOne(d => d.Trip).WithOne(p => p.Rating)
                .HasForeignKey<Rating>(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_Trips");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC071C13A19A");




            entity.Property(e => e.DeviceId).HasMaxLength(200);
            entity.Property(e => e.DeviceName).HasMaxLength(200);
            entity.Property(e => e.IsRevoked).HasComputedColumnSql("(case when [RevokedAt] IS NOT NULL then (1) else (0) end)", false);
            entity.Property(e => e.JwtId).HasMaxLength(200);
            entity.Property(e => e.ReplacedByTokenHash).HasMaxLength(32);
            entity.Property(e => e.TokenHash).HasMaxLength(32);
            entity.HasIndex(e => e.TokenHash).IsUnique();
            entity.HasIndex(e => new { e.SessionId, e.RevokedAt });

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RefreshTokens_AspNetUsers")
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reports__3214EC07D235B6F9");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Reports_Status", "[Status] IN ('Pending', 'Resolved', 'Rejected')");
            });


            entity.Property(e => e.Status)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Pending')");
            entity.Property(e => e.Subject).HasMaxLength(255);

            entity.HasOne(d => d.Trip).WithMany(p => p.Reports)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK_Complaint_Trip");

            entity.HasOne(d => d.User).WithMany(p => p.Reports)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaint_User");
        });

        modelBuilder.Entity<RouteDeviation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RouteDev__3214EC07CBFC6AE6");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_RouteDeviations_DistanceDeviationMeters", "[DistanceDeviationMeters] >= 0");
                tb.HasCheckConstraint("CK_RouteDeviations_Location", "[Location].STSrid = 4326");
            });

        });

        modelBuilder.Entity<ServiceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3214EC07737B7BD1");


            entity.Property(e => e.ServiceName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SOSAlert>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SOSAlert__3214EC07C31DC631");

            entity.ToTable("SOSAlerts", tb =>
            {
                tb.HasCheckConstraint("CK_SOSAlerts_SOSStatus", "[SOSStatus] IN ('Active', 'Resolved', 'Cancelled')");
                tb.HasCheckConstraint("CK_SOSAlerts_Location", "[Location].STSrid = 4326");
            });


            entity.Property(e => e.SOSStatus)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Active')");

            entity.HasOne(d => d.ResolvedByUser).WithMany(p => p.SOSAlertResolvedByUsers)
                .HasForeignKey(d => d.ResolvedByUserId)
                .HasConstraintName("FK_SOSAlerts_ResolvedBy");

            entity.HasOne(d => d.TriggeredByUser).WithMany(p => p.SOSAlertTriggeredByUsers)
                .HasForeignKey(d => d.TriggeredByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOSAlerts_TriggeredBy");

            entity.HasOne(d => d.Trip).WithMany(p => p.SOSAlerts)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOSAlerts_Trips");
        });

        modelBuilder.Entity<SurgePricingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SurgePri__3214EC075AB58DD8");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_SurgePricingRules_SurgeMultiplier", "[SurgeMultiplier] >= 1");
            });

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RuleName).HasMaxLength(100);
            entity.Property(e => e.SurgeMultiplier)
                .HasDefaultValue(1.00m)
                .HasColumnType("decimal(3, 2)");
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SystemSe__3214EC071B6F3002");


            entity.Property(e => e.SettingKey)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Trips__3214EC073D1A47E2");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Trips_TripStatus", "[TripStatus] IN ('ACCEPTED', 'DRIVER_ARRIVING', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')");
            });





            entity.Property(e => e.CancellationReason).HasMaxLength(255);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsSOSActivated)
                .HasDefaultValue(false)
                .HasColumnName("IsSOSActivated");
            entity.Property(e => e.TripStatus)
                .HasConversion<string>()
                .HasMaxLength(30)
                .HasDefaultValueSql("('ACCEPTED')");

            entity.HasOne(d => d.Booking).WithOne(p => p.Trip)
                .HasForeignKey<Trip>(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_Bookings");

            entity.HasOne(d => d.CancelledByUser).WithMany(p => p.Trips)
                .HasForeignKey(d => d.CancelledByUserId)
                .HasConstraintName("FK_Trips_CancelledBy");

            // A driver can have many historical trips.
            // The filtered unique index UX_Trips_Driver_Active already guarantees only one active trip at a time.
            entity.HasOne(d => d.Driver).WithMany()
                .HasForeignKey(d => d.DriverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_DriverProfiles");
        });

        modelBuilder.Entity<TripShare>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripShar__3214EC079FAF0E0E");


            entity.Property(e => e.ShareToken)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.RecipientUser).WithMany(p => p.TripShareRecipientUsers)
                .HasForeignKey(d => d.RecipientUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_Recipient");

            entity.HasOne(d => d.SharedByUser).WithMany(p => p.TripShareSharedByUsers)
                .HasForeignKey(d => d.SharedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_SharedBy");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripShares)
                .HasForeignKey(d => d.TripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_Trips");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vehicles__3214EC07353CD60C");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_Vehicles_RequiredLicenseClass", "[RequiredLicenseClass] IN ('A1', 'A', 'B', 'C1', 'C', 'D1', 'D2', 'D')");
                tb.HasCheckConstraint("CK_Vehicles_VehicleType", "[VehicleType] IN ('Motorbike', 'Car')");
                tb.HasCheckConstraint("CK_Vehicles_EngineType", "[EngineType] IN ('ICE', 'EV')");
                tb.HasCheckConstraint("CK_Vehicles_TransmissionType", "[TransmissionType] IN ('Manual', 'Automatic', 'None')");
            });


            entity.Property(e => e.BrandModel).HasMaxLength(100);
            entity.Property(e => e.Color).HasMaxLength(30);
            entity.Property(e => e.EngineType)
                .HasConversion<string>()
                .HasMaxLength(20);
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.PlateNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RequiredLicenseClass)
                .HasConversion<string>()
                .HasMaxLength(10);
            entity.Property(e => e.TransmissionType)
                .HasConversion<string>()
                .HasMaxLength(20);
            entity.Property(e => e.VehicleType)
                .HasConversion<string>()
                .HasMaxLength(20);

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Vehicles)
                .HasForeignKey(d => d.OwnerUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehicles_AspNetUsers");
        });

        modelBuilder.Entity<WalletTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WalletTr__3214EC0740D81F8C");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_WalletTransactions_TransactionType", "[TransactionType] IN ('Income', 'Withdrawal', 'Penalty', 'Bonus')");
                tb.HasCheckConstraint("CK_WalletTransactions_Amount", "[Amount] > 0");
            });


            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.TransactionType)
                .HasConversion<string>()
                .HasMaxLength(20);

            entity.HasOne(d => d.Trip).WithMany(p => p.WalletTransactions)
                .HasForeignKey(d => d.TripId)
                .HasConstraintName("FK_WalletTransaction_Trip");

            entity.HasOne(d => d.Wallet).WithMany(p => p.WalletTransactions)
                .HasForeignKey(d => d.WalletId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WalletTransaction_Wallet");
        });

        modelBuilder.Entity<WithdrawalRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Withdraw__3214EC07E0586027");

            entity.ToTable(tb =>
            {
                tb.HasCheckConstraint("CK_WithdrawalRequests_Amount", "[Amount] > 0");
                tb.HasCheckConstraint("CK_WithdrawalRequests_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
            });


            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BankAccountName).HasMaxLength(150);
            entity.Property(e => e.BankAccountNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BankName).HasMaxLength(100);
            entity.Property(e => e.RejectionReason).HasMaxLength(255);
            entity.Property(e => e.Status)
                .HasConversion<string>()
                .HasMaxLength(20)
                .HasDefaultValueSql("('Pending')");

            entity.HasOne(d => d.Wallet).WithMany(p => p.WithdrawalRequests)
                .HasForeignKey(d => d.WalletId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Withdrawal_Wallet");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
