// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SafeRide.Domain.Entities;

namespace SafeRide.Infrastructure.Persistence;

public partial class ApplicationDBContext : DbContext
{
    public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AppRole> AppRoles { get; set; }

    public virtual DbSet<AppUser> AppUsers { get; set; }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingPromotion> BookingPromotions { get; set; }

    public virtual DbSet<DriverKyc> DriverKycs { get; set; }

    public virtual DbSet<DriverProfile> DriverProfiles { get; set; }

    public virtual DbSet<DriverWallet> DriverWallets { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Otpverification> Otpverifications { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PricingRule> PricingRules { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<RouteDeviation> RouteDeviations { get; set; }

    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

    public virtual DbSet<SOSAlert> Sosalerts { get; set; }

    public virtual DbSet<SurgePricingRule> SurgePricingRules { get; set; }

    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    public virtual DbSet<Trip> Trips { get; set; }

    public virtual DbSet<TripCallLog> TripCallLogs { get; set; }

    public virtual DbSet<TripMessage> TripMessages { get; set; }

    public virtual DbSet<TripShare> TripShares { get; set; }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

    public virtual DbSet<WithdrawalRequest> WithdrawalRequests { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AppRole>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<AppUser>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AppRole>().WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_Roles"),
                    l => l.HasOne<AppUser>().WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_AspNetUserRoles_Users"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                    });
        });

        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Bookings__3214EC07DF5E0D8A");

            entity.HasIndex(e => new { e.ScheduledAt, e.BookingStatus }, "IX_Bookings_ScheduledAt_BookingStatus").HasFilter("([BookingType]='Scheduled' AND [BookingStatus]='SEARCHING')");

            entity.Property(e => e.BookingSource).HasDefaultValue("Manual");
            entity.Property(e => e.BookingStatus).HasDefaultValue("SEARCHING");
            entity.Property(e => e.BookingType).HasDefaultValue("Now");

            entity.HasOne(d => d.CancelledByNavigation).WithMany(p => p.BookingCancelledByNavigations).HasConstraintName("FK_Bookings_CancelledBy");

            entity.HasOne(d => d.Customer).WithMany(p => p.BookingCustomers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_AspNetUsers");

            entity.HasOne(d => d.PricingRule).WithMany(p => p.Bookings).HasConstraintName("FK_Bookings_PricingRule");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_ServiceType");

            entity.HasOne(d => d.SurgePricingRule).WithMany(p => p.Bookings).HasConstraintName("FK_Bookings_SurgeRule");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Vehicle");
        });

        modelBuilder.Entity<BookingPromotion>(entity =>
        {
            entity.HasKey(e => new { e.BookingId, e.PromotionId }).HasName("PK__BookingP__96B95811ED1297F3");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPromotions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPromotion_Booking");

            entity.HasOne(d => d.Promotion).WithMany(p => p.BookingPromotions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingPromotion_Promotion");
        });

        modelBuilder.Entity<DriverKyc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DriverKy__3214EC07EBC3BC61");
            entity.HasIndex(e => e.LicenseNumber, "UX_DriverKyc_LicenseNumber").IsUnique()
        .HasFilter("([LicenseNumber] IS NOT NULL)");
            entity.HasIndex(e => e.ExpiryDate, "IX_DriverKyc_ExpiryDate").HasFilter("([ExpiryDate] IS NOT NULL)");

            entity.Property(e => e.KycStatus).HasDefaultValue("Pending");

            entity.HasOne(d => d.Driver).WithMany(p => p.DriverKycs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DriverKyc_AspNetUsers");
        });

        modelBuilder.Entity<DriverProfile>(entity =>
        {
            entity.HasKey(e => e.DriverId).HasName("PK__DriverPr__F1B1CD0412E4EAAD");
            entity.HasIndex(e => e.IdentityCardNumber, "UX_DriverProfiles_IdentityCardNumber").IsUnique();

            entity.Property(e => e.DriverId).ValueGeneratedNever();
            entity.Property(e => e.ExperienceYears).HasDefaultValue(0);
            entity.Property(e => e.WorkStatus).HasDefaultValue("Offline");

            entity.HasOne(d => d.Driver).WithOne(p => p.DriverProfile)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DriverProfiles_AspNetUsers");
        });

        modelBuilder.Entity<DriverWallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DriverWa__3214EC070819237D");

            entity.HasOne(d => d.Driver).WithOne(p => p.DriverWallet)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wallet_Driver");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifica__3214EC0798D6859A");

            entity.HasIndex(e => new { e.UserId, e.IsRead }, "IX_Notifications_UserId_IsRead").HasFilter("([IsRead]=(0))");

            entity.Property(e => e.IsRead).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notifications_AspNetUsers");
        });

        modelBuilder.Entity<Otpverification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OTPVerif__3214EC0769AEC1B8");

            entity.Property(e => e.IsUsed).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.Otpverifications)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OTPVerifications_AspNetUsers");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC076B3B84FA");

            entity.Property(e => e.Currency).HasDefaultValue("VND");
            entity.Property(e => e.PaymentStatus).HasDefaultValue("Pending");

            entity.HasOne(d => d.Trip).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Trips");
        });

        modelBuilder.Entity<PricingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PricingR__3214EC0703A9EAC0");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.ServiceType).WithMany(p => p.PricingRules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PricingRules_ServiceType");
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Promotio__3214EC0721CE1B49");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxUsageCount).HasDefaultValue(100);
            entity.Property(e => e.UsageLimitPerUser).HasDefaultValue(1);
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ratings__3214EC076CE7FD35");

            entity.HasOne(d => d.Customer).WithMany(p => p.Ratings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_Customers");

            entity.HasOne(d => d.Driver).WithMany(p => p.Ratings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_DriverProfiles");

            entity.HasOne(d => d.Trip).WithOne(p => p.Rating)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Ratings_Trips");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Reports__3214EC07D539F805");

            entity.Property(e => e.Status).HasDefaultValue("Pending");

            entity.HasOne(d => d.Trip).WithMany(p => p.Reports).HasConstraintName("FK_Complaint_Trip");

            entity.HasOne(d => d.User).WithMany(p => p.Reports)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Complaint_User");
        });

        modelBuilder.Entity<RouteDeviation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RouteDev__3214EC07F96E40CA");

            entity.HasOne(d => d.Trip).WithMany(p => p.RouteDeviations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RouteDeviations_Trips");
        });

        modelBuilder.Entity<ServiceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3214EC07F380868F");
        });

        modelBuilder.Entity<SOSAlert>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SOSAlert__3214EC0723A2E1A0");

            entity.HasIndex(e => new { e.SOSStatus, e.CreatedAt }, "IX_SOSAlerts_SOSStatus_CreatedAt")
                .IsDescending(false, true)
                .HasFilter("([SOSStatus]='Active')");

            entity.Property(e => e.SOSStatus).HasDefaultValue("Active");

            entity.HasOne(d => d.ResolvedByUser).WithMany(p => p.SosalertResolvedByUsers).HasConstraintName("FK_SOSAlerts_ResolvedBy");

            entity.HasOne(d => d.TriggeredByUser).WithMany(p => p.SosalertTriggeredByUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOSAlerts_TriggeredBy");

            entity.HasOne(d => d.Trip).WithMany(p => p.SOSAlerts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SOSAlerts_Trips");
        });

        modelBuilder.Entity<SurgePricingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SurgePri__3214EC07B99C2770");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SurgeMultiplier).HasDefaultValue(1.00m);
        });

        modelBuilder.Entity<SystemSetting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SystemSe__3214EC0703E85C4A");
        });

        modelBuilder.Entity<Trip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Trips__3214EC07B42E350F");
            entity.HasIndex(e => e.DriverId, "UX_Trips_Driver_Active")
                .IsUnique()
                .HasFilter("([TripStatus] IN ('ACCEPTED', 'ARRIVED', 'IN_PROGRESS'))");
            
            entity.HasIndex(e => new { e.DriverId, e.CompletedAt }, "IX_Trips_DriverId_CompletedAt")
                .IsDescending(false, true)
                .HasFilter("([TripStatus]='COMPLETED')");

            entity.HasIndex(e => new { e.IsSOSActivated, e.TripStatus }, "IX_Trips_IsSOSActivated_TripStatus").HasFilter("([IsSOSActivated]=(1))");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsSOSActivated).HasDefaultValue(false);
            entity.Property(e => e.TripStatus).HasDefaultValue("ACCEPTED");

            entity.HasOne(d => d.Booking).WithOne(p => p.Trip)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_Bookings");

            entity.HasOne(d => d.CancelledByUser).WithMany(p => p.Trips).HasConstraintName("FK_Trips_CancelledBy");

            entity.HasOne(d => d.Driver).WithMany(p => p.Trips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Trips_DriverProfiles");
        });

        modelBuilder.Entity<TripCallLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripCall__3214EC07C33418E0");

            entity.HasOne(d => d.Caller).WithMany(p => p.TripCallLogCallers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CallLogs_Caller");

            entity.HasOne(d => d.Receiver).WithMany(p => p.TripCallLogReceivers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CallLogs_Receiver");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripCallLogs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CallLogs_Trips");
        });

        modelBuilder.Entity<TripMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripMess__3214EC07FE8198CD");

            entity.HasIndex(e => new { e.TripId, e.IsRead }, "IX_TripMessages_TripId_IsRead").HasFilter("([IsRead]=(0))");

            entity.HasOne(d => d.Sender).WithMany(p => p.TripMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripMessages_Users");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripMessages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripMessages_Trips");
        });

        modelBuilder.Entity<TripShare>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TripShar__3214EC074659F5A3");

            entity.HasOne(d => d.RecipientUser).WithMany(p => p.TripShareRecipientUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_Recipient");

            entity.HasOne(d => d.SharedByUser).WithMany(p => p.TripShareSharedByUsers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_SharedBy");

            entity.HasOne(d => d.Trip).WithMany(p => p.TripShares)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TripShares_Trips");
        });

        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Vehicles__3214EC07490A52FE");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Vehicles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehicles_AspNetUsers");
        });

        modelBuilder.Entity<WalletTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WalletTr__3214EC07F7EEDF26");

            entity.HasOne(d => d.Trip).WithMany(p => p.WalletTransactions).HasConstraintName("FK_WalletTransaction_Trip");

            entity.HasOne(d => d.Wallet).WithMany(p => p.WalletTransactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WalletTransaction_Wallet");
        });

        modelBuilder.Entity<WithdrawalRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Withdraw__3214EC07CEDDF1A8");

            entity.Property(e => e.Status).HasDefaultValue("Pending");

            entity.HasOne(d => d.Wallet).WithMany(p => p.WithdrawalRequests)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Withdrawal_Wallet");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}