//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable enable
//using System;
//using System.Collections.Generic;
//using Microsoft.EntityFrameworkCore;

//namespace SafeRide.Domain12.Entities;

//public partial class ApplicationDbContext : DbContext
//{
//    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

//    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

//    public virtual DbSet<Booking> Bookings { get; set; }

//    public virtual DbSet<BookingPromotion> BookingPromotions { get; set; }

//    public virtual DbSet<DriverKyc> DriverKycs { get; set; }

//    public virtual DbSet<DriverProfile> DriverProfiles { get; set; }

//    public virtual DbSet<DriverWallet> DriverWallets { get; set; }

//    public virtual DbSet<Notification> Notifications { get; set; }

//    public virtual DbSet<Payment> Payments { get; set; }

//    public virtual DbSet<PricingRule> PricingRules { get; set; }

//    public virtual DbSet<Promotion> Promotions { get; set; }

//    public virtual DbSet<Rating> Ratings { get; set; }

//    public virtual DbSet<Report> Reports { get; set; }

//    public virtual DbSet<RouteDeviation> RouteDeviations { get; set; }

//    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

//    public virtual DbSet<SOSAlert> SOSAlerts { get; set; }

//    public virtual DbSet<SurgePricingRule> SurgePricingRules { get; set; }

//    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

//    public virtual DbSet<Trip> Trips { get; set; }

//    public virtual DbSet<TripShare> TripShares { get; set; }

//    public virtual DbSet<Vehicle> Vehicles { get; set; }

//    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

//    public virtual DbSet<WithdrawalRequest> WithdrawalRequests { get; set; }

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<AspNetRole>(entity =>
//        {
//            entity.HasIndex(e => e.NormalizedName, "UX_AspNetRoles_NormalizedName")
//                .IsUnique()
//                .HasFilter("([NormalizedName] IS NOT NULL)");

//            entity.Property(e => e.Id).ValueGeneratedNever();
//            entity.Property(e => e.Name).HasMaxLength(256);
//            entity.Property(e => e.NormalizedName).HasMaxLength(256);
//        });

//        modelBuilder.Entity<AspNetUser>(entity =>
//        {
//            entity.HasIndex(e => e.IsActive, "IX_AspNetUsers_IsActive");

//            entity.HasIndex(e => e.NormalizedEmail, "IX_AspNetUsers_NormalizedEmail");

//            entity.HasIndex(e => e.NormalizedUserName, "UX_AspNetUsers_NormalizedUserName")
//                .IsUnique()
//                .HasFilter("([NormalizedUserName] IS NOT NULL)");

//            entity.HasIndex(e => e.PhoneNumber, "UX_AspNetUsers_PhoneNumber")
//                .IsUnique()
//                .HasFilter("([PhoneNumber] IS NOT NULL)");

//            entity.Property(e => e.Id).ValueGeneratedNever();
//            entity.Property(e => e.AvatarUrl).HasMaxLength(500);
//            entity.Property(e => e.BanReason).HasMaxLength(500);
//            entity.Property(e => e.Email).HasMaxLength(256);
//            entity.Property(e => e.FullName).HasMaxLength(250);
//            entity.Property(e => e.Gender)
//                .HasMaxLength(10)
//                .IsUnicode(false);
//            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
//            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
//            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
//            entity.Property(e => e.UserName).HasMaxLength(256);

//            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
//                .UsingEntity<Dictionary<string, object>>(
//                    "AspNetUserRole",
//                    r => r.HasOne<AspNetRole>().WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK_AspNetUserRoles_Roles"),
//                    l => l.HasOne<AspNetUser>().WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK_AspNetUserRoles_Users"),
//                    j =>
//                    {
//                        j.HasKey("UserId", "RoleId");
//                        j.ToTable("AspNetUserRoles");
//                    });
//        });

//        modelBuilder.Entity<Booking>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Bookings__3214EC073A8063CD");

//            entity.HasIndex(e => new { e.BookingStatus, e.CreatedAt }, "IX_Bookings_BookingStatus_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.CustomerId, e.BookingStatus, e.CreatedAt }, "IX_Bookings_CustomerId_BookingStatus_CreatedAt").IsDescending(false, false, true);

//            entity.HasIndex(e => new { e.ScheduledAt, e.BookingStatus }, "IX_Bookings_ScheduledAt_BookingStatus").HasFilter("([BookingType]='Scheduled' AND [BookingStatus]='SEARCHING_DRIVER')");

//            entity.HasIndex(e => new { e.VehicleId, e.BookingStatus }, "IX_Bookings_VehicleId_BookingStatus");

//            entity.HasIndex(e => e.DestinationLocation, "SIDX_Bookings_DestinationLocation");

//            entity.HasIndex(e => e.PickupLocation, "SIDX_Bookings_PickupLocation");

//            entity.Property(e => e.BookingSource)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Manual");
//            entity.Property(e => e.BookingStatus)
//                .HasMaxLength(30)
//                .IsUnicode(false)
//                .HasDefaultValue("SEARCHING_DRIVER");
//            entity.Property(e => e.BookingType)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Now");
//            entity.Property(e => e.CancellationReason).HasMaxLength(255);
//            entity.Property(e => e.DestinationAddress).HasMaxLength(255);
//            entity.Property(e => e.EstimatedDistanceKm).HasColumnType("decimal(10, 2)");
//            entity.Property(e => e.EstimatedFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PickupAddress).HasMaxLength(255);
//            entity.Property(e => e.SpecialRequest).HasMaxLength(500);

//            entity.HasOne(d => d.CancelledByNavigation).WithMany(p => p.BookingCancelledByNavigations)
//                .HasForeignKey(d => d.CancelledBy)
//                .HasConstraintName("FK_Bookings_CancelledBy");

//            entity.HasOne(d => d.Customer).WithMany(p => p.BookingCustomers)
//                .HasForeignKey(d => d.CustomerId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Bookings_AspNetUsers");

//            entity.HasOne(d => d.PricingRule).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.PricingRuleId)
//                .HasConstraintName("FK_Bookings_PricingRule");

//            entity.HasOne(d => d.ServiceType).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.ServiceTypeId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Booking_ServiceType");

//            entity.HasOne(d => d.SurgePricingRule).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.SurgePricingRuleId)
//                .HasConstraintName("FK_Bookings_SurgeRule");

//            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.VehicleId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Booking_Vehicle");
//        });

//        modelBuilder.Entity<BookingPromotion>(entity =>
//        {
//            entity.HasKey(e => new { e.BookingId, e.PromotionId }).HasName("PK__BookingP__96B958114224E6FD");

//            entity.HasIndex(e => e.PromotionId, "IX_BookingPromotions_PromotionId");

//            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");

//            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPromotions)
//                .HasForeignKey(d => d.BookingId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_BookingPromotion_Booking");

//            entity.HasOne(d => d.Promotion).WithMany(p => p.BookingPromotions)
//                .HasForeignKey(d => d.PromotionId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_BookingPromotion_Promotion");
//        });

//        modelBuilder.Entity<DriverKyc>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__DriverKy__3214EC075745B3C5");

//            entity.ToTable("DriverKyc");

//            entity.HasIndex(e => new { e.DriverId, e.KycStatus }, "IX_DriverKyc_DriverId_KycStatus");

//            entity.HasIndex(e => e.ExpiryDate, "IX_DriverKyc_ExpiryDate").HasFilter("([ExpiryDate] IS NOT NULL)");

//            entity.HasIndex(e => e.KycStatus, "IX_DriverKyc_KycStatus");

//            entity.HasIndex(e => e.DocumentNumber, "UQ__DriverKy__68993918BE326D6A").IsUnique();

//            entity.Property(e => e.BackImageUrl).HasMaxLength(500);
//            entity.Property(e => e.DocumentNumber)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.DocumentType).HasMaxLength(50);
//            entity.Property(e => e.FileUrl).HasMaxLength(500);
//            entity.Property(e => e.FrontImageUrl).HasMaxLength(500);
//            entity.Property(e => e.KycStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.LicenseClass)
//                .HasMaxLength(10)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Driver).WithMany(p => p.DriverKycs)
//                .HasForeignKey(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_DriverKyc_AspNetUsers");
//        });

//        modelBuilder.Entity<DriverProfile>(entity =>
//        {
//            entity.HasKey(e => e.DriverId).HasName("PK__DriverPr__F1B1CD046AA3E9C5");

//            entity.HasIndex(e => e.LastActiveAt, "IX_DriverProfiles_LastActiveAt").IsDescending();

//            entity.HasIndex(e => e.WorkStatus, "IX_DriverProfiles_WorkStatus");

//            entity.HasIndex(e => e.IdentityCardNumber, "UQ__DriverPr__59CD51214079FE3B").IsUnique();

//            entity.Property(e => e.DriverId).ValueGeneratedNever();
//            entity.Property(e => e.ExperienceYears).HasDefaultValue(0);
//            entity.Property(e => e.IdentityCardNumber)
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.WorkStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Offline");

//            entity.HasOne(d => d.Driver).WithOne(p => p.DriverProfile)
//                .HasForeignKey<DriverProfile>(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_DriverProfiles_AspNetUsers");
//        });

//        modelBuilder.Entity<DriverWallet>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__DriverWa__3214EC0723702C3C");

//            entity.HasIndex(e => e.DriverId, "UQ__DriverWa__F1B1CD05347E350B").IsUnique();

//            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(18, 2)");

//            entity.HasOne(d => d.Driver).WithOne(p => p.DriverWallet)
//                .HasForeignKey<DriverWallet>(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Wallet_Driver");
//        });

//        modelBuilder.Entity<Notification>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Notifica__3214EC07BC6B781B");

//            entity.HasIndex(e => new { e.UserId, e.IsRead, e.SentAt }, "IX_Notifications_UserId_IsRead_SentAt").IsDescending(false, false, true);

//            entity.HasIndex(e => new { e.UserId, e.SentAt }, "IX_Notifications_UserId_Unread")
//                .IsDescending(false, true)
//                .HasFilter("([IsRead]=(0))");

//            entity.Property(e => e.IsRead).HasDefaultValue(false);
//            entity.Property(e => e.NotificationType)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.Title).HasMaxLength(255);

//            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
//                .HasForeignKey(d => d.UserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Notifications_AspNetUsers");
//        });

//        modelBuilder.Entity<Payment>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC076511D9DA");

//            entity.HasIndex(e => new { e.PaymentStatus, e.CreatedAt }, "IX_Payments_PaymentStatus_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => e.TransactionReference, "IX_Payments_TransactionReference").HasFilter("([TransactionReference] IS NOT NULL)");

//            entity.HasIndex(e => new { e.TripId, e.PaymentStatus }, "IX_Payments_TripId_PaymentStatus");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.Currency)
//                .HasMaxLength(10)
//                .IsUnicode(false)
//                .HasDefaultValue("VND");
//            entity.Property(e => e.PaymentMethod)
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.PaymentStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.TransactionReference)
//                .HasMaxLength(100)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Trip).WithMany(p => p.Payments)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Payments_Trips");
//        });

//        modelBuilder.Entity<PricingRule>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__PricingR__3214EC07CFB6D6FF");

//            entity.HasIndex(e => new { e.VehicleClass, e.ServiceTypeId, e.IsActive }, "IX_PricingRules_VehicleClass_ServiceTypeId_IsActive");

//            entity.Property(e => e.BaseFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.MinFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PricePerHour).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PricePerKm).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.VehicleClass)
//                .HasMaxLength(10)
//                .IsUnicode(false);

//            entity.HasOne(d => d.ServiceType).WithMany(p => p.PricingRules)
//                .HasForeignKey(d => d.ServiceTypeId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_PricingRules_ServiceType");
//        });

//        modelBuilder.Entity<Promotion>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Promotio__3214EC07CE4C05F3");

//            entity.HasIndex(e => new { e.IsActive, e.EndDate }, "IX_Promotions_IsActive_EndDate");

//            entity.HasIndex(e => e.PromotionCode, "UQ__Promotio__A617E4B6B34722A6").IsUnique();

//            entity.Property(e => e.DiscountType)
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.MaxUsageCount).HasDefaultValue(100);
//            entity.Property(e => e.MaximumDiscountValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.MinimumOrderValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PromotionCode)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.UsageLimitPerUser).HasDefaultValue(1);
//        });

//        modelBuilder.Entity<Rating>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Ratings__3214EC07E3A4C19E");

//            entity.HasIndex(e => new { e.CustomerId, e.CreatedAt }, "IX_Ratings_CustomerId_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.DriverId, e.RatingScore }, "IX_Ratings_DriverId_RatingScore");

//            entity.HasIndex(e => e.TripId, "UQ__Ratings__51DC713F62DF69B5").IsUnique();

//            entity.Property(e => e.Comment).HasMaxLength(1000);

//            entity.HasOne(d => d.Customer).WithMany(p => p.Ratings)
//                .HasForeignKey(d => d.CustomerId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_Customers");

//            entity.HasOne(d => d.Driver).WithMany(p => p.Ratings)
//                .HasForeignKey(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_DriverProfiles");

//            entity.HasOne(d => d.Trip).WithOne(p => p.Rating)
//                .HasForeignKey<Rating>(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_Trips");
//        });

//        modelBuilder.Entity<Report>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Reports__3214EC07D235B6F9");

//            entity.HasIndex(e => new { e.Status, e.CreatedAt }, "IX_Reports_Status_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "IX_Reports_UserId_CreatedAt").IsDescending(false, true);

//            entity.Property(e => e.Status)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.Subject).HasMaxLength(255);

//            entity.HasOne(d => d.Trip).WithMany(p => p.Reports)
//                .HasForeignKey(d => d.TripId)
//                .HasConstraintName("FK_Complaint_Trip");

//            entity.HasOne(d => d.User).WithMany(p => p.Reports)
//                .HasForeignKey(d => d.UserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Complaint_User");
//        });

//        modelBuilder.Entity<RouteDeviation>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__RouteDev__3214EC07CBFC6AE6");

//            entity.HasIndex(e => new { e.TripId, e.CreatedAt }, "IX_RouteDeviations_TripId_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => e.Location, "SIDX_RouteDeviations_Location");

//            entity.HasOne(d => d.Trip).WithMany(p => p.RouteDeviations)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_RouteDeviations_Trips");
//        });

//        modelBuilder.Entity<ServiceType>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3214EC07737B7BD1");

//            entity.HasIndex(e => e.ServiceName, "UQ__ServiceT__A42B5F9967F1266C").IsUnique();

//            entity.Property(e => e.ServiceName)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//        });

//        modelBuilder.Entity<SOSAlert>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SOSAlert__3214EC07C31DC631");

//            entity.ToTable("SOSAlerts");

//            entity.HasIndex(e => new { e.SOSStatus, e.CreatedAt }, "IX_SOSAlerts_SOSStatus_CreatedAt")
//                .IsDescending(false, true)
//                .HasFilter("([SOSStatus]='Active')");

//            entity.HasIndex(e => e.TripId, "IX_SOSAlerts_TripId");

//            entity.HasIndex(e => e.Location, "SIDX_SOSAlerts_Location");

//            entity.Property(e => e.EmergencyMessage).HasMaxLength(500);
//            entity.Property(e => e.SOSStatus)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Active")
//                .HasColumnName("SOSStatus");

//            entity.HasOne(d => d.ResolvedByUser).WithMany(p => p.SOSAlertResolvedByUsers)
//                .HasForeignKey(d => d.ResolvedByUserId)
//                .HasConstraintName("FK_SOSAlerts_ResolvedBy");

//            entity.HasOne(d => d.TriggeredByUser).WithMany(p => p.SOSAlertTriggeredByUsers)
//                .HasForeignKey(d => d.TriggeredByUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_SOSAlerts_TriggeredBy");

//            entity.HasOne(d => d.Trip).WithMany(p => p.SOSAlerts)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_SOSAlerts_Trips");
//        });

//        modelBuilder.Entity<SurgePricingRule>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SurgePri__3214EC075AB58DD8");

//            entity.HasIndex(e => e.IsActive, "IX_SurgePricingRules_IsActive");

//            entity.Property(e => e.AppliedDays)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.RuleName).HasMaxLength(100);
//            entity.Property(e => e.SurgeMultiplier)
//                .HasDefaultValue(1.00m)
//                .HasColumnType("decimal(3, 2)");
//        });

//        modelBuilder.Entity<SystemSetting>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SystemSe__3214EC071B6F3002");

//            entity.HasIndex(e => e.SettingKey, "UQ__SystemSe__01E719AD7145BC04").IsUnique();

//            entity.Property(e => e.SettingKey)
//                .HasMaxLength(100)
//                .IsUnicode(false);
//        });

//        modelBuilder.Entity<Trip>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Trips__3214EC073D1A47E2");

//            entity.HasIndex(e => e.BookingId, "IX_Trips_BookingId");

//            entity.HasIndex(e => new { e.DriverId, e.CompletedAt }, "IX_Trips_DriverId_CompletedAt")
//                .IsDescending(false, true)
//                .HasFilter("([TripStatus]='COMPLETED')");

//            entity.HasIndex(e => new { e.DriverId, e.TripStatus, e.CreatedAt }, "IX_Trips_DriverId_TripStatus_CreatedAt").IsDescending(false, false, true);

//            entity.HasIndex(e => new { e.IsSOSActivated, e.TripStatus }, "IX_Trips_IsSOSActivated_TripStatus").HasFilter("([IsSOSActivated]=(1))");

//            entity.HasIndex(e => new { e.TripStatus, e.CreatedAt }, "IX_Trips_TripStatus_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => e.BookingId, "UQ__Trips__73951AEC8B040468").IsUnique();

//            entity.HasIndex(e => e.DriverId, "UX_Trips_Driver_Active")
//                .IsUnique()
//                .HasFilter("([TripStatus] IN ('ACCEPTED', 'DRIVER_ARRIVING', 'ARRIVED', 'IN_PROGRESS'))");

//            entity.Property(e => e.CancellationReason).HasMaxLength(255);
//            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
//            entity.Property(e => e.IsSOSActivated)
//                .HasDefaultValue(false)
//                .HasColumnName("IsSOSActivated");
//            entity.Property(e => e.TripStatus)
//                .HasMaxLength(30)
//                .IsUnicode(false)
//                .HasDefaultValue("ACCEPTED");

//            entity.HasOne(d => d.Booking).WithOne(p => p.Trip)
//                .HasForeignKey<Trip>(d => d.BookingId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Trips_Bookings");

//            entity.HasOne(d => d.CancelledByUser).WithMany(p => p.Trips)
//                .HasForeignKey(d => d.CancelledByUserId)
//                .HasConstraintName("FK_Trips_CancelledBy");

//            entity.HasOne(d => d.Driver).WithOne(p => p.Trip)
//                .HasForeignKey<Trip>(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Trips_DriverProfiles");
//        });

//        modelBuilder.Entity<TripShare>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__TripShar__3214EC079FAF0E0E");

//            entity.HasIndex(e => e.ShareToken, "IX_TripShares_ShareToken");

//            entity.HasIndex(e => new { e.TripId, e.ExpiresAt }, "IX_TripShares_TripId_ExpiresAt");

//            entity.HasIndex(e => e.ShareToken, "UQ__TripShar__9F895CDCD2376F1E").IsUnique();

//            entity.Property(e => e.ShareToken)
//                .HasMaxLength(100)
//                .IsUnicode(false);

//            entity.HasOne(d => d.RecipientUser).WithMany(p => p.TripShareRecipientUsers)
//                .HasForeignKey(d => d.RecipientUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_Recipient");

//            entity.HasOne(d => d.SharedByUser).WithMany(p => p.TripShareSharedByUsers)
//                .HasForeignKey(d => d.SharedByUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_SharedBy");

//            entity.HasOne(d => d.Trip).WithMany(p => p.TripShares)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_Trips");
//        });

//        modelBuilder.Entity<Vehicle>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Vehicles__3214EC07353CD60C");

//            entity.HasIndex(e => new { e.OwnerUserId, e.IsDeleted }, "IX_Vehicles_OwnerUserId_IsDeleted");

//            entity.HasIndex(e => e.PlateNumber, "IX_Vehicles_PlateNumber");

//            entity.HasIndex(e => e.PlateNumber, "UQ__Vehicles__0369262484EF4005").IsUnique();

//            entity.Property(e => e.BrandModel).HasMaxLength(100);
//            entity.Property(e => e.Color).HasMaxLength(30);
//            entity.Property(e => e.EngineType).HasMaxLength(20);
//            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
//            entity.Property(e => e.PlateNumber)
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.RequiredLicenseClass)
//                .HasMaxLength(10)
//                .IsUnicode(false);
//            entity.Property(e => e.TransmissionType).HasMaxLength(20);
//            entity.Property(e => e.VehicleType)
//                .HasMaxLength(20)
//                .IsUnicode(false);

//            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Vehicles)
//                .HasForeignKey(d => d.OwnerUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Vehicles_AspNetUsers");
//        });

//        modelBuilder.Entity<WalletTransaction>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__WalletTr__3214EC0740D81F8C");

//            entity.HasIndex(e => new { e.WalletId, e.CreatedAt }, "IX_WalletTransactions_WalletId_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.WalletId, e.TransactionType }, "IX_WalletTransactions_WalletId_TransactionType");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.Description).HasMaxLength(500);
//            entity.Property(e => e.TransactionType)
//                .HasMaxLength(20)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Trip).WithMany(p => p.WalletTransactions)
//                .HasForeignKey(d => d.TripId)
//                .HasConstraintName("FK_WalletTransaction_Trip");

//            entity.HasOne(d => d.Wallet).WithMany(p => p.WalletTransactions)
//                .HasForeignKey(d => d.WalletId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_WalletTransaction_Wallet");
//        });

//        modelBuilder.Entity<WithdrawalRequest>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Withdraw__3214EC07E0586027");

//            entity.HasIndex(e => new { e.Status, e.CreatedAt }, "IX_WithdrawalRequests_Status_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.WalletId, e.Status }, "IX_WithdrawalRequests_WalletId_Status");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.BankAccountName).HasMaxLength(150);
//            entity.Property(e => e.BankAccountNumber)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.BankName).HasMaxLength(100);
//            entity.Property(e => e.RejectionReason).HasMaxLength(255);
//            entity.Property(e => e.Status)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Pending");

//            entity.HasOne(d => d.Wallet).WithMany(p => p.WithdrawalRequests)
//                .HasForeignKey(d => d.WalletId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Withdrawal_Wallet");
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//}