//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using Microsoft.EntityFrameworkCore;

//namespace SafeRide.API.Entities;

//public partial class SAFERIDE_DBContext : DbContext
//{
//    public SAFERIDE_DBContext(DbContextOptions<SAFERIDE_DBContext> options)
//        : base(options)
//    {
//    }

//    public virtual DbSet<AppRole> AspNetRoles { get; set; }

//    public virtual DbSet<AppUser> AspNetUsers { get; set; }

//    public virtual DbSet<Booking> Bookings { get; set; }

//    public virtual DbSet<BookingPromotion> BookingPromotions { get; set; }

//    public virtual DbSet<DriverKyc> DriverKycs { get; set; }

//    public virtual DbSet<DriverProfile> DriverProfiles { get; set; }

//    public virtual DbSet<DriverWallet> DriverWallets { get; set; }

//    public virtual DbSet<Notification> Notifications { get; set; }

//    public virtual DbSet<Otpverification> Otpverifications { get; set; }

//    public virtual DbSet<Payment> Payments { get; set; }

//    public virtual DbSet<PricingRule> PricingRules { get; set; }

//    public virtual DbSet<Promotion> Promotions { get; set; }

//    public virtual DbSet<Rating> Ratings { get; set; }

//    public virtual DbSet<Report> Reports { get; set; }

//    public virtual DbSet<RouteDeviation> RouteDeviations { get; set; }

//    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

//    public virtual DbSet<SOSAlert> Sosalerts { get; set; }

//    public virtual DbSet<SurgePricingRule> SurgePricingRules { get; set; }

//    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

//    public virtual DbSet<Trip> Trips { get; set; }

//    public virtual DbSet<TripCallLog> TripCallLogs { get; set; }

//    public virtual DbSet<TripMessage> TripMessages { get; set; }

//    public virtual DbSet<TripShare> TripShares { get; set; }

//    public virtual DbSet<Vehicle> Vehicles { get; set; }

//    public virtual DbSet<WalletTransaction> WalletTransactions { get; set; }

//    public virtual DbSet<WithdrawalRequest> WithdrawalRequests { get; set; }

//    protected override void OnModelCreating(ModelBuilder modelBuilder)
//    {
//        modelBuilder.Entity<AppRole>(entity =>
//        {
//            entity.Property(e => e.Id).ValueGeneratedNever();
//            entity.Property(e => e.Name).HasMaxLength(256);
//            entity.Property(e => e.NormalizedName).HasMaxLength(256);
//        });

//        modelBuilder.Entity<AppUser>(entity =>
//        {
//            entity.HasIndex(e => e.IsActive, "IX_AspNetUsers_IsActive");

//            entity.HasIndex(e => e.NormalizedEmail, "IX_AspNetUsers_NormalizedEmail");

//            entity.Property(e => e.Id).ValueGeneratedNever();
//            entity.Property(e => e.AvatarUrl).HasMaxLength(500);
//            entity.Property(e => e.BanReason).HasMaxLength(500);
//            entity.Property(e => e.Email).HasMaxLength(256);
//            entity.Property(e => e.FullName).HasMaxLength(250);
//            entity.Property(e => e.Gender)
//                .HasMaxLength(10)
//                .IsUnicode(false);
//            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
//            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
//            entity.Property(e => e.UserName).HasMaxLength(256);

//            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
//                .UsingEntity<Dictionary<string, object>>(
//                    "AspNetUserRole",
//                    r => r.HasOne<AspNetRole>().WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK_AspNetUserRoles_Roles"),
//                    l => l.HasOne<AspNetUser>().WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.ClientSetNull)
//                        .HasConstraintName("FK_AspNetUserRoles_Users"),
//                    j =>
//                    {
//                        j.HasKey("UserId", "RoleId");
//                        j.ToTable("AspNetUserRoles");
//                    });
//        });

//        modelBuilder.Entity<Booking>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Bookings__3214EC07DF5E0D8A");

//            entity.HasIndex(e => new { e.BookingStatus, e.CreatedAt }, "IX_Bookings_BookingStatus_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.CustomerId, e.BookingStatus, e.CreatedAt }, "IX_Bookings_CustomerId_BookingStatus_CreatedAt").IsDescending(false, false, true);

//            entity.HasIndex(e => new { e.ScheduledAt, e.BookingStatus }, "IX_Bookings_ScheduledAt_BookingStatus").HasFilter("([BookingType]='Scheduled' AND [BookingStatus]='SEARCHING')");

//            entity.HasIndex(e => new { e.VehicleId, e.BookingStatus }, "IX_Bookings_VehicleId_BookingStatus");

//            entity.Property(e => e.BookingSource)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Manual");
//            entity.Property(e => e.BookingStatus)
//                .HasMaxLength(30)
//                .IsUnicode(false)
//                .HasDefaultValue("SEARCHING");
//            entity.Property(e => e.BookingType)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Now");
//            entity.Property(e => e.CancellationReason).HasMaxLength(255);
//            entity.Property(e => e.DestinationAddress).HasMaxLength(255);
//            entity.Property(e => e.EstimatedDistanceKm).HasColumnType("decimal(10, 2)");
//            entity.Property(e => e.EstimatedFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PickupAddress)
//                .IsRequired()
//                .HasMaxLength(255);
//            entity.Property(e => e.SpecialRequest).HasMaxLength(500);

//            entity.HasOne(d => d.CancelledByNavigation).WithMany(p => p.BookingCancelledByNavigations)
//                .HasForeignKey(d => d.CancelledBy)
//                .HasConstraintName("FK_Bookings_CancelledBy");

//            entity.HasOne(d => d.Customer).WithMany(p => p.BookingCustomers)
//                .HasForeignKey(d => d.CustomerId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Bookings_AspNetUsers");

//            entity.HasOne(d => d.PricingRule).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.PricingRuleId)
//                .HasConstraintName("FK_Bookings_PricingRule");

//            entity.HasOne(d => d.ServiceType).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.ServiceTypeId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Booking_ServiceType");

//            entity.HasOne(d => d.SurgePricingRule).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.SurgePricingRuleId)
//                .HasConstraintName("FK_Bookings_SurgeRule");

//            entity.HasOne(d => d.Vehicle).WithMany(p => p.Bookings)
//                .HasForeignKey(d => d.VehicleId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Booking_Vehicle");
//        });

//        modelBuilder.Entity<BookingPromotion>(entity =>
//        {
//            entity.HasKey(e => new { e.BookingId, e.PromotionId }).HasName("PK__BookingP__96B95811ED1297F3");

//            entity.HasIndex(e => e.PromotionId, "IX_BookingPromotions_PromotionId");

//            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");

//            entity.HasOne(d => d.Booking).WithMany(p => p.BookingPromotions)
//                .HasForeignKey(d => d.BookingId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_BookingPromotion_Booking");

//            entity.HasOne(d => d.Promotion).WithMany(p => p.BookingPromotions)
//                .HasForeignKey(d => d.PromotionId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_BookingPromotion_Promotion");
//        });

//        modelBuilder.Entity<DriverKyc>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__DriverKy__3214EC07EBC3BC61");

//            entity.ToTable("DriverKyc");

//            entity.HasIndex(e => new { e.DriverId, e.KycStatus }, "IX_DriverKyc_DriverId_KycStatus");

//            entity.HasIndex(e => e.ExpiryDate, "IX_DriverKyc_ExpiryDate").HasFilter("([ExpiryDate] IS NOT NULL)");

//            entity.HasIndex(e => e.KycStatus, "IX_DriverKyc_KycStatus");

//            entity.HasIndex(e => e.LicenseNumber, "UQ__DriverKy__E8890166A9AEF67E").IsUnique();

//            entity.Property(e => e.DocumentType).HasMaxLength(50);
//            entity.Property(e => e.DocumentUrl)
//                .IsRequired()
//                .HasMaxLength(255)
//                .IsUnicode(false);
//            entity.Property(e => e.KycStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.LicenseClass)
//                .HasMaxLength(10)
//                .IsUnicode(false);
//            entity.Property(e => e.LicenseNumber)
//                .HasMaxLength(50)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Driver).WithMany(p => p.DriverKycs)
//                .HasForeignKey(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_DriverKyc_AspNetUsers");
//        });

//        modelBuilder.Entity<DriverProfile>(entity =>
//        {
//            entity.HasKey(e => e.DriverId).HasName("PK__DriverPr__F1B1CD0412E4EAAD");

//            entity.HasIndex(e => e.LastActiveAt, "IX_DriverProfiles_LastActiveAt").IsDescending();

//            entity.HasIndex(e => e.WorkStatus, "IX_DriverProfiles_WorkStatus");

//            entity.HasIndex(e => e.IdentityCardNumber, "UQ__DriverPr__59CD512142E1CF59").IsUnique();

//            entity.Property(e => e.DriverId).ValueGeneratedNever();
//            entity.Property(e => e.ExperienceYears).HasDefaultValue(0);
//            entity.Property(e => e.IdentityCardNumber)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.WorkStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Offline");

//            entity.HasOne(d => d.Driver).WithOne(p => p.DriverProfile)
//                .HasForeignKey<DriverProfile>(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_DriverProfiles_AspNetUsers");
//        });

//        modelBuilder.Entity<DriverWallet>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__DriverWa__3214EC070819237D");

//            entity.HasIndex(e => e.DriverId, "UQ__DriverWa__F1B1CD059728ECFC").IsUnique();

//            entity.Property(e => e.CurrentBalance).HasColumnType("decimal(18, 2)");

//            entity.HasOne(d => d.Driver).WithOne(p => p.DriverWallet)
//                .HasForeignKey<DriverWallet>(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Wallet_Driver");
//        });

//        modelBuilder.Entity<Notification>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Notifica__3214EC0798D6859A");

//            entity.HasIndex(e => new { e.UserId, e.IsRead }, "IX_Notifications_UserId_IsRead").HasFilter("([IsRead]=(0))");

//            entity.HasIndex(e => new { e.UserId, e.IsRead, e.SentAt }, "IX_Notifications_UserId_IsRead_SentAt").IsDescending(false, false, true);

//            entity.Property(e => e.Content).IsRequired();
//            entity.Property(e => e.IsRead).HasDefaultValue(false);
//            entity.Property(e => e.NotificationType)
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.Title)
//                .IsRequired()
//                .HasMaxLength(255);

//            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
//                .HasForeignKey(d => d.UserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Notifications_AspNetUsers");
//        });

//        modelBuilder.Entity<Otpverification>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__OTPVerif__3214EC0769AEC1B8");

//            entity.ToTable("OTPVerifications");

//            entity.HasIndex(e => new { e.ExpiresAt, e.IsUsed }, "IX_OTPVerifications_ExpiresAt_IsUsed");

//            entity.HasIndex(e => new { e.UserId, e.Purpose, e.IsUsed }, "IX_OTPVerifications_UserId_Purpose_IsUsed");

//            entity.Property(e => e.IsUsed).HasDefaultValue(false);
//            entity.Property(e => e.Otpcode)
//                .IsRequired()
//                .HasMaxLength(10)
//                .IsUnicode(false)
//                .HasColumnName("OTPCode");
//            entity.Property(e => e.Purpose)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);

//            entity.HasOne(d => d.User).WithMany(p => p.Otpverifications)
//                .HasForeignKey(d => d.UserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_OTPVerifications_AspNetUsers");
//        });

//        modelBuilder.Entity<Payment>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC076B3B84FA");

//            entity.HasIndex(e => new { e.PaymentStatus, e.PaidAt }, "IX_Payments_PaymentStatus_PaidAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.TripId, e.PaymentStatus }, "IX_Payments_TripId_PaymentStatus");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.Currency)
//                .HasMaxLength(10)
//                .IsUnicode(false)
//                .HasDefaultValue("VND");
//            entity.Property(e => e.PaymentMethod)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.PaymentStatus)
//                .HasMaxLength(20)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.TransactionReference)
//                .HasMaxLength(100)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Trip).WithMany(p => p.Payments)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Payments_Trips");
//        });

//        modelBuilder.Entity<PricingRule>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__PricingR__3214EC0703A9EAC0");

//            entity.HasIndex(e => new { e.VehicleClass, e.ServiceTypeId, e.IsActive }, "IX_PricingRules_VehicleClass_ServiceTypeId_IsActive");

//            entity.Property(e => e.BaseFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.MinFare).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PricePerHour).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PricePerKm).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.VehicleClass)
//                .IsRequired()
//                .HasMaxLength(10)
//                .IsUnicode(false);

//            entity.HasOne(d => d.ServiceType).WithMany(p => p.PricingRules)
//                .HasForeignKey(d => d.ServiceTypeId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_PricingRules_ServiceType");
//        });

//        modelBuilder.Entity<Promotion>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Promotio__3214EC0721CE1B49");

//            entity.HasIndex(e => new { e.IsActive, e.EndDate }, "IX_Promotions_IsActive_EndDate");

//            entity.HasIndex(e => e.PromotionCode, "UQ__Promotio__A617E4B608DA0B31").IsUnique();

//            entity.Property(e => e.DiscountType)
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.DiscountValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.MaxUsageCount).HasDefaultValue(100);
//            entity.Property(e => e.MaximumDiscountValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.MinimumOrderValue).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.PromotionCode)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.UsageLimitPerUser).HasDefaultValue(1);
//        });

//        modelBuilder.Entity<Rating>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Ratings__3214EC076CE7FD35");

//            entity.HasIndex(e => new { e.CustomerId, e.CreatedAt }, "IX_Ratings_CustomerId_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.DriverId, e.RatingScore }, "IX_Ratings_DriverId_RatingScore");

//            entity.HasIndex(e => e.TripId, "UQ__Ratings__51DC713F6F452792").IsUnique();

//            entity.Property(e => e.Comment).HasMaxLength(1000);

//            entity.HasOne(d => d.Customer).WithMany(p => p.Ratings)
//                .HasForeignKey(d => d.CustomerId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_Customers");

//            entity.HasOne(d => d.Driver).WithMany(p => p.Ratings)
//                .HasForeignKey(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_DriverProfiles");

//            entity.HasOne(d => d.Trip).WithOne(p => p.Rating)
//                .HasForeignKey<Rating>(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Ratings_Trips");
//        });

//        modelBuilder.Entity<Report>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Reports__3214EC07D539F805");

//            entity.HasIndex(e => new { e.Status, e.CreatedAt }, "IX_Reports_Status_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "IX_Reports_UserId_CreatedAt").IsDescending(false, true);

//            entity.Property(e => e.Description).IsRequired();
//            entity.Property(e => e.Status)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Pending");
//            entity.Property(e => e.Subject)
//                .IsRequired()
//                .HasMaxLength(255);

//            entity.HasOne(d => d.Trip).WithMany(p => p.Reports)
//                .HasForeignKey(d => d.TripId)
//                .HasConstraintName("FK_Complaint_Trip");

//            entity.HasOne(d => d.User).WithMany(p => p.Reports)
//                .HasForeignKey(d => d.UserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Complaint_User");
//        });

//        modelBuilder.Entity<RouteDeviation>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__RouteDev__3214EC07F96E40CA");

//            entity.HasIndex(e => new { e.TripId, e.CreatedAt }, "IX_RouteDeviations_TripId_CreatedAt").IsDescending(false, true);

//            entity.HasOne(d => d.Trip).WithMany(p => p.RouteDeviations)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_RouteDeviations_Trips");
//        });

//        modelBuilder.Entity<ServiceType>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3214EC07F380868F");

//            entity.HasIndex(e => e.ServiceName, "UQ__ServiceT__A42B5F993C233A5F").IsUnique();

//            entity.Property(e => e.ServiceName)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);
//        });

//        modelBuilder.Entity<SOSAlert>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SOSAlert__3214EC0723A2E1A0");

//            entity.ToTable("SOSAlerts");

//            entity.HasIndex(e => new { e.SOSStatus, e.CreatedAt }, "IX_SOSAlerts_SOSStatus_CreatedAt")
//                .IsDescending(false, true)
//                .HasFilter("([SOSStatus]='Active')");

//            entity.HasIndex(e => e.TripId, "IX_SOSAlerts_TripId");

//            entity.Property(e => e.EmergencyMessage).HasMaxLength(500);
//            entity.Property(e => e.SOSStatus)
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Active")
//                .HasColumnName("SOSStatus");

//            entity.HasOne(d => d.ResolvedByUser).WithMany(p => p.SosalertResolvedByUsers)
//                .HasForeignKey(d => d.ResolvedByUserId)
//                .HasConstraintName("FK_SOSAlerts_ResolvedBy");

//            entity.HasOne(d => d.TriggeredByUser).WithMany(p => p.SosalertTriggeredByUsers)
//                .HasForeignKey(d => d.TriggeredByUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_SOSAlerts_TriggeredBy");

//            entity.HasOne(d => d.Trip).WithMany(p => p.Sosalerts)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_SOSAlerts_Trips");
//        });

//        modelBuilder.Entity<SurgePricingRule>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SurgePri__3214EC07B99C2770");

//            entity.HasIndex(e => e.IsActive, "IX_SurgePricingRules_IsActive");

//            entity.Property(e => e.AppliedDays)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.IsActive).HasDefaultValue(true);
//            entity.Property(e => e.RuleName)
//                .IsRequired()
//                .HasMaxLength(100);
//            entity.Property(e => e.SurgeMultiplier)
//                .HasDefaultValue(1.00m)
//                .HasColumnType("decimal(3, 2)");
//        });

//        modelBuilder.Entity<SystemSetting>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__SystemSe__3214EC0703E85C4A");

//            entity.HasIndex(e => e.SettingKey, "UQ__SystemSe__01E719AD4F79BCC9").IsUnique();

//            entity.Property(e => e.SettingKey)
//                .IsRequired()
//                .HasMaxLength(100)
//                .IsUnicode(false);
//        });

//        modelBuilder.Entity<Trip>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Trips__3214EC07B42E350F");

//            entity.HasIndex(e => new { e.DriverId, e.CompletedAt }, "IX_Trips_DriverId_CompletedAt")
//                .IsDescending(false, true)
//                .HasFilter("([TripStatus]='COMPLETED')");

//            entity.HasIndex(e => new { e.DriverId, e.TripStatus, e.CreatedAt }, "IX_Trips_DriverId_TripStatus_CreatedAt").IsDescending(false, false, true);

//            entity.HasIndex(e => new { e.IsSosactivated, e.TripStatus }, "IX_Trips_IsSOSActivated_TripStatus").HasFilter("([IsSOSActivated]=(1))");

//            entity.HasIndex(e => new { e.TripStatus, e.CreatedAt }, "IX_Trips_TripStatus_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => e.BookingId, "UQ__Trips__73951AEC460777C9").IsUnique();

//            entity.Property(e => e.CancellationReason).HasMaxLength(255);
//            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
//            entity.Property(e => e.IsSosactivated)
//                .HasDefaultValue(false)
//                .HasColumnName("IsSOSActivated");
//            entity.Property(e => e.TripStatus)
//                .HasMaxLength(30)
//                .IsUnicode(false)
//                .HasDefaultValue("ACCEPTED");

//            entity.HasOne(d => d.Booking).WithOne(p => p.Trip)
//                .HasForeignKey<Trip>(d => d.BookingId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Trips_Bookings");

//            entity.HasOne(d => d.CancelledByUser).WithMany(p => p.Trips)
//                .HasForeignKey(d => d.CancelledByUserId)
//                .HasConstraintName("FK_Trips_CancelledBy");

//            entity.HasOne(d => d.Driver).WithMany(p => p.Trips)
//                .HasForeignKey(d => d.DriverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Trips_DriverProfiles");
//        });

//        modelBuilder.Entity<TripCallLog>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__TripCall__3214EC07C33418E0");

//            entity.HasIndex(e => new { e.TripId, e.StartedAt }, "IX_TripCallLogs_TripId_StartedAt").IsDescending(false, true);

//            entity.Property(e => e.CallStatus)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Caller).WithMany(p => p.TripCallLogCallers)
//                .HasForeignKey(d => d.CallerId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_CallLogs_Caller");

//            entity.HasOne(d => d.Receiver).WithMany(p => p.TripCallLogReceivers)
//                .HasForeignKey(d => d.ReceiverId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_CallLogs_Receiver");

//            entity.HasOne(d => d.Trip).WithMany(p => p.TripCallLogs)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_CallLogs_Trips");
//        });

//        modelBuilder.Entity<TripMessage>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__TripMess__3214EC07FE8198CD");

//            entity.HasIndex(e => new { e.TripId, e.IsRead }, "IX_TripMessages_TripId_IsRead").HasFilter("([IsRead]=(0))");

//            entity.HasIndex(e => new { e.TripId, e.SentAt }, "IX_TripMessages_TripId_SentAt").IsDescending(false, true);

//            entity.Property(e => e.Content)
//                .IsRequired()
//                .HasMaxLength(1000);

//            entity.HasOne(d => d.Sender).WithMany(p => p.TripMessages)
//                .HasForeignKey(d => d.SenderId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripMessages_Users");

//            entity.HasOne(d => d.Trip).WithMany(p => p.TripMessages)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripMessages_Trips");
//        });

//        modelBuilder.Entity<TripShare>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__TripShar__3214EC074659F5A3");

//            entity.HasIndex(e => new { e.TripId, e.ExpiresAt }, "IX_TripShares_TripId_ExpiresAt");

//            entity.HasIndex(e => e.ShareToken, "UQ__TripShar__9F895CDCE0F255B9").IsUnique();

//            entity.Property(e => e.ShareToken)
//                .IsRequired()
//                .HasMaxLength(100)
//                .IsUnicode(false);

//            entity.HasOne(d => d.RecipientUser).WithMany(p => p.TripShareRecipientUsers)
//                .HasForeignKey(d => d.RecipientUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_Recipient");

//            entity.HasOne(d => d.SharedByUser).WithMany(p => p.TripShareSharedByUsers)
//                .HasForeignKey(d => d.SharedByUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_SharedBy");

//            entity.HasOne(d => d.Trip).WithMany(p => p.TripShares)
//                .HasForeignKey(d => d.TripId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_TripShares_Trips");
//        });

//        modelBuilder.Entity<Vehicle>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Vehicles__3214EC07490A52FE");

//            entity.HasIndex(e => new { e.OwnerUserId, e.IsDeleted }, "IX_Vehicles_OwnerUserId_IsDeleted");

//            entity.HasIndex(e => e.PlateNumber, "UQ__Vehicles__03692624959587B0").IsUnique();

//            entity.Property(e => e.BrandModel)
//                .IsRequired()
//                .HasMaxLength(100);
//            entity.Property(e => e.Color).HasMaxLength(30);
//            entity.Property(e => e.EngineType)
//                .IsRequired()
//                .HasMaxLength(20);
//            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
//            entity.Property(e => e.PlateNumber)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false);
//            entity.Property(e => e.RequiredLicenseClass)
//                .IsRequired()
//                .HasMaxLength(10)
//                .IsUnicode(false);
//            entity.Property(e => e.TransmissionType)
//                .IsRequired()
//                .HasMaxLength(20);

//            entity.HasOne(d => d.OwnerUser).WithMany(p => p.Vehicles)
//                .HasForeignKey(d => d.OwnerUserId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Vehicles_AspNetUsers");
//        });

//        modelBuilder.Entity<WalletTransaction>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__WalletTr__3214EC07F7EEDF26");

//            entity.HasIndex(e => new { e.WalletId, e.CreatedAt }, "IX_WalletTransactions_WalletId_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.WalletId, e.TransactionType }, "IX_WalletTransactions_WalletId_TransactionType");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.Description).HasMaxLength(500);
//            entity.Property(e => e.TransactionType)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false);

//            entity.HasOne(d => d.Trip).WithMany(p => p.WalletTransactions)
//                .HasForeignKey(d => d.TripId)
//                .HasConstraintName("FK_WalletTransaction_Trip");

//            entity.HasOne(d => d.Wallet).WithMany(p => p.WalletTransactions)
//                .HasForeignKey(d => d.WalletId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_WalletTransaction_Wallet");
//        });

//        modelBuilder.Entity<WithdrawalRequest>(entity =>
//        {
//            entity.HasKey(e => e.Id).HasName("PK__Withdraw__3214EC07CEDDF1A8");

//            entity.HasIndex(e => new { e.Status, e.CreatedAt }, "IX_WithdrawalRequests_Status_CreatedAt").IsDescending(false, true);

//            entity.HasIndex(e => new { e.WalletId, e.Status }, "IX_WithdrawalRequests_WalletId_Status");

//            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
//            entity.Property(e => e.BankAccountName)
//                .IsRequired()
//                .HasMaxLength(150);
//            entity.Property(e => e.BankAccountNumber)
//                .IsRequired()
//                .HasMaxLength(50)
//                .IsUnicode(false);
//            entity.Property(e => e.BankName)
//                .IsRequired()
//                .HasMaxLength(100);
//            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
//            entity.Property(e => e.RejectionReason).HasMaxLength(255);
//            entity.Property(e => e.Status)
//                .IsRequired()
//                .HasMaxLength(20)
//                .IsUnicode(false)
//                .HasDefaultValue("Pending");

//            entity.HasOne(d => d.Wallet).WithMany(p => p.WithdrawalRequests)
//                .HasForeignKey(d => d.WalletId)
//                .OnDelete(DeleteBehavior.ClientSetNull)
//                .HasConstraintName("FK_Withdrawal_Wallet");
//        });

//        OnModelCreatingPartial(modelBuilder);
//    }

//    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
//}