const now = new Date().toISOString();
export const MOCK_DRIVERS = [
    {
        id: '1',
        driverCode: 'SR-20240312',
        name: 'Nguyễn Văn An',
        email: 'an.nguyen@example.com',
        phone: '+84 901 234 567',
        avatar: '#5a6c3a',
        avatarUrl: null,
        initials: 'NA',
        rating: 4.9,
        trips: 128,
        joinDate: '12/03/2023',
        registeredDate: '12/03/2023',
        city: 'TP. Hà Nội',
        status: 'active',
        workStatus: 'Online',
        isActive: true,
        banReason: null,
        documents: [
            {
                id: 1,
                documentType: 'ID_CARD',
                documentNumber: '001090123456',
                licenseClass: null,
                frontImageUrl: null,
                backImageUrl: null,
                fileUrl: null,
                issueDate: null,
                expiryDate: null,
                kycStatus: 'Approved',
                createdAt: now,
                verifiedAt: now,
                rejectionReason: null,
            },
        ],
        kyc: {
            citizenId: '001090123456',
            fullName: 'NGUYỄN VĂN AN',
            dateOfBirth: '22/04/1990',
            gender: 'Nam',
            address: '45 Trần Hưng Đạo, Hoàn Kiếm, TP. Hà Nội',
        },
    },
    {
        id: '2',
        driverCode: 'SR-20240915',
        name: 'Nguyễn Phan Tuấn',
        email: 'tuan.nguyen@saferide.com',
        phone: '+84 908 123 456',
        avatar: '#073946',
        avatarUrl: null,
        initials: 'NT',
        rating: null,
        trips: 0,
        joinDate: 'Mới đây',
        registeredDate: '12/05/2024',
        city: 'TP. Ht Chi Minh',
        status: 'pending_kyc',
        workStatus: 'Offline',
        isActive: true,
        banReason: null,
        documents: [
            {
                id: 2,
                documentType: 'ID_CARD',
                documentNumber: '079090012345',
                licenseClass: null,
                frontImageUrl: null,
                backImageUrl: null,
                fileUrl: null,
                issueDate: null,
                expiryDate: null,
                kycStatus: 'Pending',
                createdAt: now,
                verifiedAt: null,
                rejectionReason: null,
            },
        ],
        kyc: {
            citizenId: '079090012345',
            fullName: 'NGUYỄN PHAN TUẤN',
            dateOfBirth: '15/09/1992',
            gender: 'Nam',
            address: '123 Lê Lợi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
        },
    },
    {
        id: '3',
        driverCode: 'SR-20221105',
        name: 'Lê Minh Tuấn',
        email: 'tuan.le@provider.vn',
        phone: '+84 912 233 445',
        avatar: '#4a5a6c',
        avatarUrl: null,
        initials: 'LT',
        rating: 3.2,
        trips: 42,
        joinDate: '05/11/2022',
        registeredDate: '05/11/2022',
        city: 'TP. Đà Nẵng',
        status: 'blocked',
        workStatus: 'Offline',
        isActive: false,
        banReason: 'Khóa bởi quản trị viên',
        documents: [
            {
                id: 3,
                documentType: 'ID_CARD',
                documentNumber: '048092334455',
                licenseClass: null,
                frontImageUrl: null,
                backImageUrl: null,
                fileUrl: null,
                issueDate: null,
                expiryDate: null,
                kycStatus: 'Approved',
                createdAt: now,
                verifiedAt: now,
                rejectionReason: null,
            },
        ],
        kyc: {
            citizenId: '048092334455',
            fullName: 'LÊ MINH TUẤN',
            dateOfBirth: '03/12/1989',
            gender: 'Nam',
            address: '18 Bạch Đằng, Hải Châu, TP. Đà Nẵng',
        },
    },
];
