// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using SafeRide.Infrastructure.Persistence;

#nullable disable

namespace SafeRide.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.AspNetRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.AspNetUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<string>("BookingSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Point>("DestinationLocation")
                        .HasColumnType("geography");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<long?>("PricingRuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoutePolyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecialRequest")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("SurgePricingRuleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__3214EC073A8063CD");

                    b.HasIndex("BookingStatus");

                    b.HasIndex("BookingType");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PricingRuleId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SurgePricingRuleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_BookingSource", "[BookingSource] IN ('Manual', 'VoiceCommand', 'Scheduled')");

                            t.HasCheckConstraint("CK_Bookings_BookingStatus", "[BookingStatus] IN ('PendingSchedule', 'Searching', 'DriverAssigned', 'Cancelled', 'Expired', 'Completed')");

                            t.HasCheckConstraint("CK_Bookings_BookingType", "[BookingType] IN ('Now', 'Scheduled')");

                            t.HasCheckConstraint("CK_Bookings_DestinationLocation", "[DestinationLocation] IS NULL OR [DestinationLocation].STSrid = 4326");

                            t.HasCheckConstraint("CK_Bookings_EstimatedDistanceKm", "[EstimatedDistanceKm] IS NULL OR [EstimatedDistanceKm] >= 0");

                            t.HasCheckConstraint("CK_Bookings_EstimatedDurationMinutes", "[EstimatedDurationMinutes] IS NULL OR [EstimatedDurationMinutes] >= 0");

                            t.HasCheckConstraint("CK_Bookings_EstimatedFare", "[EstimatedFare] >= 0");

                            t.HasCheckConstraint("CK_Bookings_PickupLocation", "[PickupLocation].STSrid = 4326");

                            t.HasCheckConstraint("CK_Bookings_ScheduledAt", "([BookingType] = 'Now' AND [ScheduledAt] IS NULL) OR ([BookingType] = 'Scheduled' AND [ScheduledAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.BookingDriverOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OfferedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id")
                        .HasName("PK_BookingDriverOffers");

                    b.HasIndex("BookingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("BookingId", "DriverId")
                        .IsUnique();

                    b.HasIndex("BookingId", "OfferStatus");

                    b.HasIndex("DriverId", "OfferStatus");

                    b.HasIndex("OfferStatus", "ExpiresAt");

                    b.ToTable("BookingDriverOffers", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDriverOffers_ExpiresAt", "[ExpiresAt] > [OfferedAt]");

                            t.HasCheckConstraint("CK_BookingDriverOffers_OfferStatus", "[OfferStatus] IN ('Sent', 'DriverAccepted', 'CustomerConfirmed', 'Rejected', 'Expired', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.BookingPromotion", b =>
                {
                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingId", "PromotionId")
                        .HasName("PK__BookingP__96B958114224E6FD");

                    b.HasIndex("PromotionId");

                    b.ToTable("BookingPromotions", t =>
                        {
                            t.HasCheckConstraint("CK_BookingPromotions_DiscountAmount", "[DiscountAmount] >= 0");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverKyc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BackImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FrontImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.Property<string>("LicenseClass")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__DriverKy__3214EC075745B3C5");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverKyc", null, t =>
                        {
                            t.HasCheckConstraint("CK_DriverKyc_DocumentFile", "[FrontImageUrl] IS NOT NULL OR [BackImageUrl] IS NOT NULL OR [FileUrl] IS NOT NULL");

                            t.HasCheckConstraint("CK_DriverKyc_DocumentType", "[DocumentType] IN ('ID_CARD', 'DRIVING_LICENSE', 'CRIMINAL_RECORD')");

                            t.HasCheckConstraint("CK_DriverKyc_DrivingLicense", "[DocumentType] <> 'DRIVING_LICENSE' OR ([DocumentNumber] IS NOT NULL AND [LicenseClass] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DriverKyc_KycStatus", "[KycStatus] IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_DriverKyc_LicenseClass", "[LicenseClass] IS NULL OR [LicenseClass] IN ('Old_A1', 'Old_A2', 'Old_B1', 'Old_B2', 'A1', 'A', 'B')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverProfile", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Offline')");

                    b.HasKey("DriverId")
                        .HasName("PK__DriverPr__F1B1CD046AA3E9C5");

                    b.ToTable("DriverProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_DriverProfiles_ExperienceYears", "[ExperienceYears] IS NULL OR [ExperienceYears] >= 0");

                            t.HasCheckConstraint("CK_DriverProfiles_WorkStatus", "[WorkStatus] IN ('Online', 'Offline', 'Busy')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__DriverWa__3214EC0723702C3C");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("DriverWallets", t =>
                        {
                            t.HasCheckConstraint("CK_DriverWallets_CurrentBalance", "[CurrentBalance] >= 0");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC07BC6B781B");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC076511D9DA");

                    b.HasIndex("TripId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_PaymentMethod", "[PaymentMethod] IN ('QR', 'CASH')");

                            t.HasCheckConstraint("CK_Payments_PaymentStatus", "[PaymentStatus] IN ('Pending', 'Success', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("CK_Payments_TransactionReference", "([PaymentMethod] = 'QR' AND [TransactionReference] IS NOT NULL) OR ([PaymentMethod] = 'CASH' AND [TransactionReference] IS NULL)");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.PricingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MinFare")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PricePerHour")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PricePerKm")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__PricingR__3214EC07CFB6D6FF");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("PricingRules", t =>
                        {
                            t.HasCheckConstraint("CK_PricingRules_BaseFare", "[BaseFare] >= 0");

                            t.HasCheckConstraint("CK_PricingRules_MinFare", "[MinFare] >= 0");

                            t.HasCheckConstraint("CK_PricingRules_PricePerHour", "[PricePerHour] IS NULL OR [PricePerHour] >= 0");

                            t.HasCheckConstraint("CK_PricingRules_PricePerKm", "[PricePerKm] IS NULL OR [PricePerKm] >= 0");

                            t.HasCheckConstraint("CK_PricingRules_VehicleClass", "[VehicleClass] IN ('A1', 'A', 'B')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxUsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<decimal>("MaximumDiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageLimitPerUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Promotio__3214EC07CE4C05F3");

                    b.ToTable("Promotions", t =>
                        {
                            t.HasCheckConstraint("CK_Promotions_Date", "[EndDate] > [StartDate]");

                            t.HasCheckConstraint("CK_Promotions_DiscountType", "[DiscountType] IS NULL OR [DiscountType] IN ('Percentage', 'Fixed')");

                            t.HasCheckConstraint("CK_Promotions_DiscountValue", "[DiscountValue] > 0");

                            t.HasCheckConstraint("CK_Promotions_OrderValue", "[MinimumOrderValue] >= 0 AND [MaximumDiscountValue] >= 0");

                            t.HasCheckConstraint("CK_Promotions_Usage", "[MaxUsageCount] > 0 AND [CurrentUsageCount] >= 0 AND [CurrentUsageCount] <= [MaxUsageCount] AND [UsageLimitPerUser] > 0");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RatingScore")
                        .HasColumnType("int");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Ratings__3214EC07E3A4C19E");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Ratings_Customer_Driver", "[CustomerId] <> [DriverId]");

                            t.HasCheckConstraint("CK_Ratings_RatingScore", "[RatingScore] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsRevoked")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(case when [RevokedAt] IS NOT NULL then (1) else (0) end)", false);

                    b.Property<string>("JwtId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("ReplacedByTokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC071C13A19A");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "RevokedAt");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Reports__3214EC07D235B6F9");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports", t =>
                        {
                            t.HasCheckConstraint("CK_Reports_Status", "[Status] IN ('Pending', 'Resolved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.RouteDeviation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistanceDeviationMeters")
                        .HasColumnType("int");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__RouteDev__3214EC07CBFC6AE6");

                    b.HasIndex("TripId");

                    b.ToTable("RouteDeviations", t =>
                        {
                            t.HasCheckConstraint("CK_RouteDeviations_DistanceDeviationMeters", "[DistanceDeviationMeters] >= 0");

                            t.HasCheckConstraint("CK_RouteDeviations_Location", "[Location].STSrid = 4326");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.SOSAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SOSStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Active')");

                    b.Property<Guid>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__SOSAlert__3214EC07C31DC631");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("TripId");

                    b.ToTable("SOSAlerts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SOSAlerts_Location", "[Location].STSrid = 4326");

                            t.HasCheckConstraint("CK_SOSAlerts_SOSStatus", "[SOSStatus] IN ('Active', 'Resolved', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceT__3214EC07737B7BD1");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.SurgePricingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppliedDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("SurgeMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3, 2)")
                        .HasDefaultValue(1.00m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__SurgePri__3214EC075AB58DD8");

                    b.ToTable("SurgePricingRules", t =>
                        {
                            t.HasCheckConstraint("CK_SurgePricingRules_SurgeMultiplier", "[SurgeMultiplier] >= 1");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__SystemSe__3214EC071B6F3002");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DriverAssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSOSActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSOSActivated");

                    b.Property<string>("RoutePolyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValueSql("('ACCEPTED')");

                    b.HasKey("Id")
                        .HasName("PK__Trips__3214EC073D1A47E2");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("DriverId");

                    b.ToTable("Trips", t =>
                        {
                            t.HasCheckConstraint("CK_Trips_TripStatus", "[TripStatus] IN ('ACCEPTED', 'DRIVER_ARRIVING', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.TripShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__TripShar__3214EC079FAF0E0E");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("TripId");

                    b.ToTable("TripShares");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BrandModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EngineCapacityCc")
                        .HasColumnType("int");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RequiredLicenseClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Vehicles__3214EC07353CD60C");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_EngineCapacityCc", "[EngineCapacityCc] IS NULL OR [EngineCapacityCc] > 0");

                            t.HasCheckConstraint("CK_Vehicles_EngineType", "[EngineType] IN ('ICE', 'EV')");

                            t.HasCheckConstraint("CK_Vehicles_RequiredLicenseClass", "[RequiredLicenseClass] IN ('A1', 'A', 'B')");

                            t.HasCheckConstraint("CK_Vehicles_TransmissionType", "[TransmissionType] IN ('Manual', 'Automatic', 'None')");

                            t.HasCheckConstraint("CK_Vehicles_VehicleType", "[VehicleType] IN ('Motorbike', 'Car')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__WalletTr__3214EC0740D81F8C");

                    b.HasIndex("TripId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_WalletTransactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_WalletTransactions_TransactionType", "[TransactionType] IN ('Income', 'Withdrawal', 'Penalty', 'Bonus')");
                        });
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BankAccountName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('Pending')");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Withdraw__3214EC07E0586027");

                    b.HasIndex("WalletId");

                    b.ToTable("WithdrawalRequests", t =>
                        {
                            t.HasCheckConstraint("CK_WithdrawalRequests_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_WithdrawalRequests_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_Roles");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "CancelledByNavigation")
                        .WithMany("BookingCancelledByNavigations")
                        .HasForeignKey("CancelledBy")
                        .HasConstraintName("FK_Bookings_CancelledBy");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "Customer")
                        .WithMany("BookingCustomers")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_AspNetUsers");

                    b.HasOne("SafeRide.Domain.Entities.PricingRule", "PricingRule")
                        .WithMany("Bookings")
                        .HasForeignKey("PricingRuleId")
                        .HasConstraintName("FK_Bookings_PricingRule");

                    b.HasOne("SafeRide.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_ServiceType");

                    b.HasOne("SafeRide.Domain.Entities.SurgePricingRule", "SurgePricingRule")
                        .WithMany("Bookings")
                        .HasForeignKey("SurgePricingRuleId")
                        .HasConstraintName("FK_Bookings_SurgeRule");

                    b.HasOne("SafeRide.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Vehicle");

                    b.Navigation("CancelledByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("PricingRule");

                    b.Navigation("ServiceType");

                    b.Navigation("SurgePricingRule");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.BookingDriverOffer", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Booking", "Booking")
                        .WithMany("DriverOffers")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDriverOffers_Bookings");

                    b.HasOne("SafeRide.Domain.Entities.DriverProfile", "Driver")
                        .WithMany("BookingDriverOffers")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingDriverOffers_DriverProfiles");

                    b.Navigation("Booking");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.BookingPromotion", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingPromotion_Booking");

                    b.HasOne("SafeRide.Domain.Entities.Promotion", "Promotion")
                        .WithMany("BookingPromotions")
                        .HasForeignKey("PromotionId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingPromotion_Promotion");

                    b.Navigation("Booking");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverKyc", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "Driver")
                        .WithMany("DriverKycs")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_DriverKyc_AspNetUsers");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverProfile", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "Driver")
                        .WithOne("DriverProfile")
                        .HasForeignKey("SafeRide.Domain.Entities.DriverProfile", "DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_DriverProfiles_AspNetUsers");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverWallet", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.DriverProfile", "Driver")
                        .WithOne("DriverWallet")
                        .HasForeignKey("SafeRide.Domain.Entities.DriverWallet", "DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_Wallet_Driver");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("Payments")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Trips");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.PricingRule", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("PricingRules")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_PricingRules_ServiceType");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Rating", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Customers");

                    b.HasOne("SafeRide.Domain.Entities.DriverProfile", "Driver")
                        .WithMany("Ratings")
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_DriverProfiles");

                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithOne("Rating")
                        .HasForeignKey("SafeRide.Domain.Entities.Rating", "TripId")
                        .IsRequired()
                        .HasConstraintName("FK_Ratings_Trips");

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_AspNetUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Report", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("Reports")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_Complaint_Trip");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Complaint_User");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.RouteDeviation", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("RouteDeviations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.SOSAlert", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "ResolvedByUser")
                        .WithMany("SOSAlertResolvedByUsers")
                        .HasForeignKey("ResolvedByUserId")
                        .HasConstraintName("FK_SOSAlerts_ResolvedBy");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "TriggeredByUser")
                        .WithMany("SOSAlertTriggeredByUsers")
                        .HasForeignKey("TriggeredByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_SOSAlerts_TriggeredBy");

                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("SOSAlerts")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_SOSAlerts_Trips");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("TriggeredByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Trip", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Booking", "Booking")
                        .WithOne("Trip")
                        .HasForeignKey("SafeRide.Domain.Entities.Trip", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Trips_Bookings");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "CancelledByUser")
                        .WithMany("Trips")
                        .HasForeignKey("CancelledByUserId")
                        .HasConstraintName("FK_Trips_CancelledBy");

                    b.HasOne("SafeRide.Domain.Entities.DriverProfile", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .IsRequired()
                        .HasConstraintName("FK_Trips_DriverProfiles");

                    b.Navigation("Booking");

                    b.Navigation("CancelledByUser");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.TripShare", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "RecipientUser")
                        .WithMany("TripShareRecipientUsers")
                        .HasForeignKey("RecipientUserId")
                        .IsRequired()
                        .HasConstraintName("FK_TripShares_Recipient");

                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "SharedByUser")
                        .WithMany("TripShareSharedByUsers")
                        .HasForeignKey("SharedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_TripShares_SharedBy");

                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("TripShares")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK_TripShares_Trips");

                    b.Navigation("RecipientUser");

                    b.Navigation("SharedByUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.AspNetUser", "OwnerUser")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_AspNetUsers");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.Trip", "Trip")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_WalletTransaction_Trip");

                    b.HasOne("SafeRide.Domain.Entities.DriverWallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FK_WalletTransaction_Wallet");

                    b.Navigation("Trip");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.WithdrawalRequest", b =>
                {
                    b.HasOne("SafeRide.Domain.Entities.DriverWallet", "Wallet")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FK_Withdrawal_Wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.AspNetUser", b =>
                {
                    b.Navigation("BookingCancelledByNavigations");

                    b.Navigation("BookingCustomers");

                    b.Navigation("DriverKycs");

                    b.Navigation("DriverProfile");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("SOSAlertResolvedByUsers");

                    b.Navigation("SOSAlertTriggeredByUsers");

                    b.Navigation("TripShareRecipientUsers");

                    b.Navigation("TripShareSharedByUsers");

                    b.Navigation("Trips");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingPromotions");

                    b.Navigation("DriverOffers");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverProfile", b =>
                {
                    b.Navigation("BookingDriverOffers");

                    b.Navigation("DriverWallet");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.DriverWallet", b =>
                {
                    b.Navigation("WalletTransactions");

                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.PricingRule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("BookingPromotions");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.SurgePricingRule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Rating");

                    b.Navigation("Reports");

                    b.Navigation("RouteDeviations");

                    b.Navigation("SOSAlerts");

                    b.Navigation("TripShares");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("SafeRide.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
